DIHT/apps/accounts/urls.py
# -*- coding: utf-8 -*-
"""
    Авторы: Гусев Илья
    Дата создания: 22/07/2015
    Версия Python: 3.4
    Версия Django: 1.8.5
    Описание:
        URL resolver модуля accounts.
"""
from django.conf.urls import url, include
from django.views.generic import TemplateView
from accounts.views import SignUpView, ResetPasswordView, ProfileView, ProfileUpdateView, \
    CheckUniqueView, AvatarUpdateView, SignUpOkView, FindView, AddMoneyView, RemoveMoneyView, \
    ActivateView, MoneyHistoryView, UserMoneyHistoryView, AddPaymentsView, RemovePaymentsView, ChangePasswordView, \
    ApproveMoneyView, KeysView, KeyCreateView, KeyUpdateView, KeyDeleteView, ChargeView, ChangePassIdView, \
    YandexMoneyFormView, YandexMoneyCardRedirView, YandexMoneyRedirView

urlpatterns = [
    url(r'^signup/$', SignUpView.as_view(), name='signup'),
    url(r'^signup_ok/$', SignUpOkView.as_view(), name='signup_ok'),
    url(r'^charge/$', ChargeView.as_view(), name='charge'),

    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),

    url(r'^reset_password/$', ResetPasswordView.as_view(), name='reset_password'),
    url(r'^reset_password_ok/$', TemplateView.as_view(template_name='accounts/reset_password_ok.html'), name='reset_password_ok'),

    url(r'^profile/(?P<pk>[0-9]*)/$', ProfileView.as_view(), name='profile'),
    url(r'^profile/edit/(?P<pk>[0-9]*)/$', ProfileUpdateView.as_view(), name='edit_profile'),
    url(r'^profile/add_money/(?P<pk>[0-9]*)/$', AddMoneyView.as_view(), name='add_money'),
    url(r'^profile/remove_money/(?P<pk>[0-9]*)/$', RemoveMoneyView.as_view(), name='remove_money'),
    url(r'^profile/history_money/(?P<pk>[0-9]*)/$', UserMoneyHistoryView.as_view(), name='history_money'),
    url(r'^profile/add_payments/(?P<pk>[0-9]*)/$', AddPaymentsView.as_view(), name='add_payments'),
    url(r'^profile/remove_payments/(?P<pk>[0-9]*)/$', RemovePaymentsView.as_view(), name='remove_payments'),
    url(r'^profile/find/$', FindView.as_view(), name='find'),
    url(r'^profile/approve_money/(?P<pk>[0-9]*)/$', ApproveMoneyView.as_view(), name='approve_money'),

    url(r'^change_password/(?P<pk>[0-9]*)/$', ChangePasswordView.as_view(), name='change_password'),
    url(r'^change_pass_id/(?P<pk>[0-9]*)/$', ChangePassIdView.as_view(), name='change_pass_id'),
    url(r'^activate/(?P<pk>[0-9]*)/$', ActivateView.as_view(), name='activate'),
    url(r'^money_history/$', MoneyHistoryView.as_view(), name='all_money_history'),
    url(r'^keys/$', KeysView.as_view(), name='keys'),
    url(r'^keys/create/$', KeyCreateView.as_view(), name='key_create'),
    url(r'^keys/(?P<pk>[0-9]*)/delete/$', KeyDeleteView.as_view(), name='key_delete'),
    url(r'^keys/(?P<pk>[0-9]*)/update/$', KeyUpdateView.as_view(), name='key_update'),

    url(r'^check_unique/$', CheckUniqueView.as_view(), name='check_unique'),
    url(r'^avatar/change/(?P<pk>[0-9]*)/$', AvatarUpdateView.as_view(), name='change_avatar'),

    url('', include('social.apps.django_app.urls', namespace='social')),

    url(r'^yandex_money_form$', YandexMoneyFormView.as_view(), name='yandex_money_form'),
    url(r'^yandex_money_card$', YandexMoneyCardRedirView.as_view(), name='yandex_money_card'),
    url(r'^yandex_money_redir$', YandexMoneyRedirView.as_view(), name='yandex_money_redir'),
]

DIHT/apps/main/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from main.views import GymView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='home'),
    url(r'^gym/$', GymView.as_view(template_name="gym.html"), name='gym'),
    url(r'^feedback/$', TemplateView.as_view(template_name="feedback.html"), name='feedback'),
]

DIHT/apps/washing/urls.py
from django.conf.urls import url
from washing.views import IndexView, CreateRecordView, CancelRecordView, BlockDayView, UnblockDayView, CheckAccessView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^create_record/$', CreateRecordView.as_view(), name='create_record'),
    url(r'^cancel_record/$', CancelRecordView.as_view(), name='cancel_record'),
    url(r'^block_day/$', BlockDayView.as_view(), name='block_day'),
    url(r'^unblock_day/$', UnblockDayView.as_view(), name='unblock_day'),
    url(r'^access/(([0-9a-fA-F]{2}){4,10})/$', CheckAccessView.as_view(), name='check_access'),
]

DIHT/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

handler400 = 'DIHT.views.custom_400'
handler403 = 'DIHT.views.custom_403'
handler404 = 'DIHT.views.custom_404'
handler405 = 'DIHT.views.custom_405'
handler500 = 'DIHT.views.custom_500'
handler501 = 'DIHT.views.custom_501'
handler502 = 'DIHT.views.custom_502'
handler503 = 'DIHT.views.custom_503'

urlpatterns = [
    url(r'^', include('main.urls', namespace='main')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^washing/', include('washing.urls', namespace='washing')),
    url(r'^activism/', include('activism.urls', namespace='activism')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

DIHT/apps/accounts/views.py
# -*- coding: utf-8 -*-
"""
    Авторы: Гусев Илья
    Дата создания: 22/07/2015
    Версия Python: 3.4
    Версия Django: 1.8.5
    Описание:
        Логика, связанная с профилями пользователей.
        Клиентская часть в signup.js, common.js, profile.js.
        3 вида views - страница, действие, модаль (всплывающее окно).
        Все модали работают с common.js. Если видишь JSON - это туда.
"""
import os
import json
import urllib.parse
import time
from DIHT.settings import BASE_DIR
from django.core.files import File
from django.views.generic.edit import FormView, UpdateView, DeleteView
from django.views.generic import DetailView, View, TemplateView, ListView
from django.contrib.auth.models import User, Group
from django.core.urlresolvers import reverse_lazy
from django.db import transaction
from django.core.mail import EmailMessage
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.views.generic.detail import SingleObjectMixin
from django.http import HttpResponseRedirect
from braces.views import LoginRequiredMixin, UserPassesTestMixin, GroupRequiredMixin
from django.utils import timezone
from django.shortcuts import redirect
from django.conf import settings
from itertools import chain
from accounts.forms import ProfileForm, SignUpForm, ResetPasswordForm, FindForm, \
    MoneyForm, ChangePasswordForm, KeyCreateForm, KeyUpdateForm, ChangePassIdForm, YandexMoneyForm
from accounts.models import Profile, Avatar, MoneyOperation, PaymentsOperation, Key, KeyTransfer
from washing.models import BlackListRecord
from activism.views import get_level
from yandex_money.api import Wallet, ExternalPayment

import logging
logger = logging.getLogger('DIHT.custom')


class JsonErrorsMixin(object):
    """
    Mixin для правильной обработки ошибок в модальных формах.
    Клентская часть в common.js, функция view_modal_errors.
    """
    def form_invalid(self, form):
        super(JsonErrorsMixin, self).form_invalid(form)
        return JsonResponse(form.errors, status=400)


class SignUpView(FormView):
    """
    Страница регистрации пользователя. Пользователь создаётся НЕ активным, нужно подтверждение.
    Дополнительные действия - установка стандартной аватарки.
    """
    template_name = 'accounts/signup.html'
    form_class = SignUpForm
    success_url = reverse_lazy('accounts:signup_ok')

    def form_valid(self, form):
        SignUpView.register_user(form.cleaned_data)
        return super(SignUpView, self).form_valid(form)

    @classmethod
    @transaction.atomic
    def register_user(cls, form):
        user = User.objects.create_user(username=form['username'],
                                        email=form['email'],
                                        password=form['password'],
                                        first_name=form['first_name'],
                                        last_name=form['last_name'])
        Profile.objects.create(user=user,
                               room_number=form['room_number'],
                               group_number=form['group_number'],
                               money=0,
                               mobile=form['mobile'],
                               middle_name=form['middle_name'],
                               hostel=form['hostel'],
                               sex=form['sex'])

        BlackListRecord.objects.create(user=user, is_blocked=False)
        avatar = Avatar.objects.create(user=user)
        with open(os.path.join(BASE_DIR, 'DIHT/static/img/standart_avatar.png'), 'rb') as img_file:
            avatar.img.save("avatar", File(img_file), save=True)
        avatar.save()
        user.is_active = False
        user.save()
        # logger.info('Пользователь '+str(form['first_name'])+' '+str(form['last_name'])+' ('+str(form['username'])+') только что зарегистрировался на сайте.')


class ResetPasswordView(FormView):
    """
    Старница сброса пароля с отправкой письма на e-mail. Никаких проверок не делает.
    """
    template_name = 'accounts/reset_password.html'
    form_class = ResetPasswordForm
    success_url = reverse_lazy('accounts:reset_password_ok')

    def form_valid(self, form):
        user = User.objects.all().filter(username=form.cleaned_data['username'])[0]
        password = User.objects.make_random_password()
        email = EmailMessage(u'Сброс пароля', u'Новый пароль для 2ka.fizteh.ru: ' + password, to=[user.email])
        if email.send() == 1:
            user.set_password(password)
            user.save()
            # logger.info('Пользователь ' + user.get_full_name() + ' (' + user.username + ') изменил свой пароль через функцию восстановления пароля.')
        return super(ResetPasswordView, self).form_valid(form)


class CheckUniqueView(View):
    """
    Действие для проверки уникальности логина и почты.
    Клиентская часть в signup.js, функции check_username и check_email.
    """
    def get(self, request, *args, **kwargs):
        username = request.GET['username']
        email = request.GET['email']
        result = {'username': '0', 'email': '0'}
        if username != '':
            if User.objects.all().filter(username=username).exists():
                result['username'] = '1'
        if email != '':
            if User.objects.all().filter(email=email).exists():
                result['email'] = '1'
        return JsonResponse(result, status=200)


def is_user_key(user, key):
    return key.find(user.last_name + " ") != -1 and \
           key[key.find(".") - 1] == user.first_name[0] and \
           (key[key.rfind(".") - 1] == user.profile.middle_name[0] or key[key.rfind(".") - 1] == ".")


def get_plan_room(user):
    with open("plan.json", 'r') as f:
        content = f.read()
        plan = json.loads(content)
        room = ""
        neighbours = []
        for key, value in plan.items():
            if is_user_key(user, key):
                room = value
                break
        if room == "":
            return -1, neighbours
        for key, value in plan.items():
            if value == room and not is_user_key(user, key):
                neighbours.append(key)
        return room, neighbours


class ProfileView(LoginRequiredMixin, DetailView):
    """
    Страница для отображения профиля
    """
    template_name = 'accounts/profile.html'
    model = Profile

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        user = self.get_object().user
        is_charge = Group.objects.get(name="Ответственные за активистов") in self.request.user.groups.all()
        is_activist = Group.objects.get(name="Активисты") in self.request.user.groups.all()
        context['records'] = user.records.order_by('-datetime_to').reverse()
        context['task_current'] = user.task_set.exclude(status__in=['closed', 'resolved'])
        context['task_responsible'] = sorted(user.tasks_responsible.all(),
                                             key=lambda task: task.datetime_created, reverse=True)
        context['task_hours'] = user.participated.filter(task__status__in=['closed', 'resolved'])
        if user.social_auth.filter(provider='vk-oauth2').exists():
            context['vk'] = user.social_auth.get(provider='vk-oauth2').uid
        if context['profile'].group_number != '':
            grade = int(str(timezone.now().date().year)[-1]) - int(str(context['profile'].group_number)[0])
            if timezone.now().date().month >= 8:
                grade += 1
            if grade > 6 or grade < 0:
                context['grade'] = 'Выпускник/Аспирант'
            else:
                context['grade'] = str(grade) + ' курс'
        context['can_view_tasks'] = (self.request.user == user and is_activist) or self.request.user.is_superuser or is_charge
        context['moderated_money'] = sum(user.moderated_moneyoperations.filter(is_approved=False, amount__gte=0)
                                                                  .values_list('amount', flat=True))
        context['operations'] = user.pointoperations.all()
        context['op_for_hours'] = int(sum(user.participated.filter(task__status__in=['closed'])
                                              .values_list('hours', flat=True)) // 10)
        context['level'] = get_level(user)
        context['plan_room'], context['neighbours'] = get_plan_room(user)
        if 'profile_message' in self.request.session:
            context['profile_message'], context['profile_message_is_error'] = self.request.session['profile_message']
            del self.request.session['profile_message']
        else:
            context['profile_message'], context['profile_message_is_error'] = '', False
        return context


class ProfileUpdateView(LoginRequiredMixin, UserPassesTestMixin, JsonErrorsMixin, UpdateView):
    """
    Модаль для изменения профиля
    """
    model = Profile
    form_class = ProfileForm
    template_name = "accounts/edit_profile.html"
    success_url = reverse_lazy('main:home')
    raise_exception = True

    def test_func(self, user):
        return self.get_object().user == user

    def form_valid(self, form):
        super(ProfileUpdateView, self).form_valid(form)
        return JsonResponse({'url': reverse('accounts:profile', kwargs={'pk': self.get_object().pk})}, status=200)


class AvatarUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    Действие для установки аватарки.
    Клиенсткая часть в profile.js.
    """
    model = Avatar
    fields = ('img', )
    success_url = reverse_lazy('main:home')

    def test_func(self, user):
        return self.get_object().user == user


class SignUpOkView(TemplateView):
    """
    Страница успешной регистрации.
    Показывает людей, к которым нужно обращаться для подтверждения аккаунта.
    """
    template_name = 'accounts/signup_ok.html'

    def get_context_data(self, **kwargs):
        context = super(SignUpOkView, self).get_context_data(**kwargs)

DIHT/apps/main/views.py
from django.views.generic import TemplateView
from django.contrib.auth.models import User, Group


class GymView(TemplateView):
    def get_context_data(self, **kwargs):
        context = super(GymView, self).get_context_data(**kwargs)
        if Group.objects.filter(name="Ответственные за качалку").exists():
            context['charge_gym'] = Group.objects.get(name="Ответственные за качалку").user_set.all()
        return context

DIHT/views.py
from django.shortcuts import render


def custom_400(request):
    values_for_template = {}
    return render(request, 'errors/400.html', values_for_template, status=400)


def custom_403(request):
    values_for_template = {}
    return render(request, 'errors/403.html', values_for_template, status=403)


def custom_404(request):
    values_for_template = {}
    return render(request, 'errors/404.html', values_for_template, status=404)


def custom_405(request):
    values_for_template = {}
    return render(request, 'errors/405.html', values_for_template, status=405)


def custom_500(request):
    values_for_template = {}
    return render(request, 'errors/500.html', values_for_template, status=500)


def custom_501(request):
    values_for_template = {}
    return render(request, 'errors/501.html', values_for_template, status=501)


def custom_502(request):
    values_for_template = {}
    return render(request, 'errors/502.html', values_for_template, status=502)


def custom_503(request):
    values_for_template = {}
    return render(request, 'errors/503.html', values_for_template, status=503)

DIHT/templates/washing/washing.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load user_tags %}
{% block title %} Стиралка {% endblock %}
{% block washing_active %} class = "active" {% endblock %}
{% block custom_scripts %}
    <script src="{% static 'js/washing.js' %}" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html"></script>
	<link rel="stylesheet" href="{% static 'css/washing-gym.css' %}">
{% endblock %}
{% block content %}
    <style>
        td.status0{/*blocked (grey)*/
            background-color:#B4B4B4;
            text-align: center;
        }
        td.status1{/*free (green)*/
            background-color: #59B259;
            text-align: center;
            {% if user.is_authenticated and not user.black_list_record.is_blocked %}
                cursor: pointer;
            {% endif %}
        }
        td.status2{/*bought (red)*/
            text-align: center;
            background-color:#D14741;
        }
        td.status3{/*your (blue)*/
            text-align: center;
            background-color:#44AAC8;
            {% if user.is_authenticated %}
                cursor: pointer;
            {% endif %}
        }
        td {
            height: 40px;
            width: 100px;
        }
        @media (max-width: 768px) {
            td{
                font-size:12px;
                height: 30px;
            }
            th{
                font-size:13px;
            }
        }
}

    </style>
    <form method="post" class="form-inline">
    {% csrf_token %}
    <div class="col-md-10 col-md-offset-1 page-header">
        <!--<input type="hidden" name="activist" value="true">-->
        <h3 style="display:inline-block;">Стиралка</h3><div id="activist_tabs" style="display: none; margin-left: 30px;">
              <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Выбрать стиралку
              <span class="caret"></span></button>
              <ul class="dropdown-menu">
                <li><input type="submit" name="activist" value="Для активистов" id="activist_btn" class="btn btn-default" style="width: 100%"></li>
                <li><input type="submit" name="nonactivist" value="Обычная" class="btn btn-default" style="width: 100%"></li>
              </ul>
            <!--<input type="submit" name="activist" value="Для активистов" id="activist_btn" class="washing_activist_check">
            <input type="submit" name="nonactivist" value="Обычная" class="washing_activist_check">-->
            <!--<a href="#" id="activist_washing_link">Для активистов</a>--> </div>
    </div>
    </form>
	<div class="col-md-10 col-md-offset-1">
    {% if user.is_authenticated and user.black_list_record.is_blocked%}
    <div class="alert alert-danger">
        <p>Вы в чёрном списке стиралки</p>
    </div>
    {% endif %}
    <div id="usual_washing">
    <div class="row">
        <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    {%comment%}<th width="150" class="text-center">Время</th>{%endcomment%}
                    {% for machine in machines %}
                        <th class="text-center" id="machine_{{ machine.pk }}" price=" {{ machine.parameters.all }}">{{machine.name}}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for day, intervals in schedule.items %}
                <tr>
                    {% if user in charge_washing or user.is_superuser %}
                    <th scope="row"
                        style="cursor: pointer;"
                        colspan="{{ machines|length }}"
                        class="text-center btn-open-modal"
                        href="{% url 'washing:block_day' %}"
                        id="{{day| date:'d.m.Y'}}"
                        data-target="#form-modal">
                        {{day| date:"d.m.Y (l)"}}
                    </th>
                    {% else %}
                    <th scope="row"
                        colspan="{{ machines|length|add:'1' }}"
                        class="text-center">
                        {{day| date:"d.m.Y (l)"}}
                    </th>
                    {% endif %}
                </tr>
                {% for interval, records in intervals.items %}
                <tr>
                    {%comment%}<th scope="row" width="150" class="text-center">{{ interval.0|time:"H:i" }}-{{ interval.1|time:"H:i" }}</th>{%endcomment%}
                    {% for machine, record in records.items %}
                    {% if record.0 == 'OK' %}
                        {% if user.is_authenticated and not user.black_list_record.is_blocked%}
                        <td class="status1 btn-open-modal"
                            href="{% url 'washing:create_record'%}"
                            id="{{ machine.pk }} {{ day|date:'d.m.Y' }} {{ interval.0|time:'H:i' }} {{ interval.1|time:'H:i' }} {{ record.1 }}">
                            {% if machine.parameters.all.0.activist %}
                            {{ interval.0|time:'H:i' }} - {{ interval.1|time:'H:i' }}{% endif %}
                        </td>
                        {% else %}
                        <td class="status1">{% if machine.parameters.all.0.activist %}
                            {{ interval.0|time:'H:i' }} - {{ interval.1|time:'H:i' }}{% endif %}</td>
                        {% endif %}
                    {% elif record.0 == 'BUSY' %}
                        <!--<td class="status2 btn-open-modal"
                            href="{% url 'washing:cancel_record'%}"
                            id="{{ machine.pk }} {{ day|date:'d.m.Y' }} {{ interval.0|time:'H:i' }} {{ interval.1|time:'H:i' }} {{ record.1 }}">
                        {% if machine.parameters.all.0.activist %}
                            {{ interval.0|time:'H:i' }} - {{ interval.1|time:'H:i' }}{% endif %}
                        </td>-->
                    <td class="status2">
                        {% if user in charge_washing or user.is_superuser or record.3 %}
                        <center><a class="bgrey" href="{% url 'accounts:profile' pk=record.2.profile.pk%}">{{ record.2.get_full_name }}</a></center>
                        {% endif %}
                    {% if machine.parameters.all.0.activist %}
                            <div>{{ interval.0|time:'H:i' }} - {{ interval.1|time:'H:i' }}</div>{% endif %}
                    {% if user.is_authenticated and user|has_group:"Ответственные за активистов" and machine.parameters.all.0.activist %}
                    <input name="cancel_activ" id="cancel_activ_{{ record.2.id }} {{ machine.id }} {{ day|date:'d.m.Y' }} {{ interval.0|time:'H:i' }} {{ interval.1|time:'H:i' }} {{ record.1 }}"
                           class="btn btn-warning" style="width: 80px;" type="button" value="Отмена"/></td>
                        {% endif %}
                    {% elif record.0 == 'DISABLE' %}
                    <td class="status0"></td>
                    {% elif record.0 == 'YOURS' %}
                        {% if user.is_authenticated and day != current %}
                        <td class="status3 btn-open-modal"
                            href="{% url 'washing:cancel_record'%}"
                            id="{{ machine.pk }} {{ day|date:'d.m.Y' }} {{ interval.0|time:'H:i' }} {{ interval.1|time:'H:i' }} {{ record.1 }}">
                        {% if machine.parameters.all.0.activist %}
                            {{ interval.0|time:'H:i' }} - {{ interval.1|time:'H:i' }}{% endif %}
                        </td>
                        {% else %}
                        <td class="status3">{% if machine.parameters.all.0.activist %}
                            {{ interval.0|time:'H:i' }} - {{ interval.1|time:'H:i' }}{% endif %}</td>
                        {% endif %}
                    {% endif %}
                    {% endfor %}
                </tr>
                {% endfor %}
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
    </div>


    <center><a href="#" data-toggle="modal" data-target="#responsible-modal">Ответственные за стиралку</a></center><br>
    <div class="modal" id="responsible-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header"><h3>Ответственные за стиралку</h3></div>
                <div id="form-modal-body" class="modal-body">
                    {% for user in charge_washing %}
                        {{ user.get_full_name }}, комната {{ user.profile.room_number }}<br>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                </div>
            </div>
        </div>
    </div>
    <center><a href="" class="spoiler_links" style="font-size: 20px;">Инструкция</a></center><br>
     <div class="washing_instruction jumbotron" id="washing-rules" style="display: none;">
         <p class="washing-instruction-main">
            <h3 style="text-align: center;">Стиралка на 2 этаже<br> Инструкция к действию: </h3>
            <ul style="text-align: left" class="ul-washing-instruction">
                <li>1)Пополнить счёт у ответственных за стиралку. Стоимость бронирования одной машинки на одни сутки — 100 рублей.</li>
                <li>2)Записаться на сайте (в разделе «Стиралка») на свободный промежуток времени (свободный промежуток времени обозначается зеленым цветом), если нужно - на несколько.</li>
                <li>3)Ознакомиться с правилами пользования стиральной комнатой и стиральной машиной.</li>
                <li>4)Получить у ответственного за стиралку ключ от стиральной комнаты (с 19:00 до 23:00 вечером перед днем стирки).</li>
                <li>5)Вовремя подойти в стиралку (она находится в умывалке северного крыла 2 этажа) со своим порошком (должен быть для МАШИННОЙ СТИРКИ) и загрузить вещи. Поставить время стирки такое, чтобы не залезть на чужой промежуток времени.</li>
                <li>6)Вернуть ключ от стиральной машины ответственному, у которого взяли ключ.</li>
            </ul>
            В случае каких-либо непредвиденных ситуаций связаться с ответственными за стиралку.

        </p>
     </div>
    <div class="jumbotron" id="washing-rules">
        <center><h3>Правила пользования стиралкой</h3></center>

        <ol>
            <li>Студентам, пользующимся стиралкой (стиральной машиной), запрещается:
            <ul>
                <li>передавать ключ от стиралки другим лицам, без согласования с ответственным</li>
                <li>использовать стиральную машинку, на которую не были записаны</li>
                <li>оставлять неубранным&nbsp;рассыпанный&nbsp;стиральный порошок</li>
                <li>оставлять пустые коробки&nbsp;из-под порошка, пакеты&nbsp;и т.д.</li>
                <li>использовать при стирке вещества, не предназначенные для автоматических стиральных машин</li>
            </ul>
            </li>
            <li>Студенты, пользующиеся стиралкой, обязаны соблюдать правила эксплуатации машинками:
            <ul>
                <li>Не загружать в машинку более 6 кг. белья</li>
                <li>Использовать стиральную машинку только с тем номером, на которую были записаны</li>
                <li>Не открывать дверцы до разблокировки</li>
                <li>Избегать попадания мелких деталей (монеты, ключи и т.д.) в барабан машинки</li>
                <li>Стирать бюстгалтеры и вещи с мелкими твердыми предметами в специальных мешках для стирки</li>
                <li>Не оставлять белье в машинке после стирки</li>
                <li>Не смешивать белые и цветные вещи</li>
                <li>Оставлять после стирки дверцу машинки открытой</li>
                <li>Забрать высохшие вещи из стиралки в течение суток после окончания своей записи (в<span style="line-height:1.6em">зять ключ в таком случае нужно у того ответственного или заведующего, который выдал ключ по записи)</span></li>
                <li>Оперативно информировать ответственного или заведующего о выявленных неисправностях машинки</li>
            </ul>
            </li>
        </ol>
    </div>
	</div>
{% endblock %}