DIHT/apps/accounts/urls.py
# -*- coding: utf-8 -*-
"""
    Авторы: Гусев Илья
    Дата создания: 22/07/2015
    Версия Python: 3.4
    Версия Django: 1.8.5
    Описание:
        URL resolver модуля accounts.
"""
from django.conf.urls import url, include
from django.views.generic import TemplateView
from accounts.views import SignUpView, ResetPasswordView, ProfileView, ProfileUpdateView, \
    CheckUniqueView, AvatarUpdateView, SignUpOkView, FindView, AddMoneyView, RemoveMoneyView, \
    ActivateView, MoneyHistoryView, UserMoneyHistoryView, AddPaymentsView, RemovePaymentsView, ChangePasswordView, \
    ApproveMoneyView, KeysView, KeyCreateView, KeyUpdateView, KeyDeleteView, ChargeView, ChangePassIdView, \
    YandexMoneyFormView, YandexMoneyCardRedirView, YandexMoneyRedirView

urlpatterns = [
    url(r'^signup/$', SignUpView.as_view(), name='signup'),
    url(r'^signup_ok/$', SignUpOkView.as_view(), name='signup_ok'),
    url(r'^charge/$', ChargeView.as_view(), name='charge'),

    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),

    url(r'^reset_password/$', ResetPasswordView.as_view(), name='reset_password'),
    url(r'^reset_password_ok/$', TemplateView.as_view(template_name='accounts/reset_password_ok.html'), name='reset_password_ok'),

    url(r'^profile/(?P<pk>[0-9]*)/$', ProfileView.as_view(), name='profile'),
    url(r'^profile/edit/(?P<pk>[0-9]*)/$', ProfileUpdateView.as_view(), name='edit_profile'),
    url(r'^profile/add_money/(?P<pk>[0-9]*)/$', AddMoneyView.as_view(), name='add_money'),
    url(r'^profile/remove_money/(?P<pk>[0-9]*)/$', RemoveMoneyView.as_view(), name='remove_money'),
    url(r'^profile/history_money/(?P<pk>[0-9]*)/$', UserMoneyHistoryView.as_view(), name='history_money'),
    url(r'^profile/add_payments/(?P<pk>[0-9]*)/$', AddPaymentsView.as_view(), name='add_payments'),
    url(r'^profile/remove_payments/(?P<pk>[0-9]*)/$', RemovePaymentsView.as_view(), name='remove_payments'),
    url(r'^profile/find/$', FindView.as_view(), name='find'),
    url(r'^profile/approve_money/(?P<pk>[0-9]*)/$', ApproveMoneyView.as_view(), name='approve_money'),

    url(r'^change_password/(?P<pk>[0-9]*)/$', ChangePasswordView.as_view(), name='change_password'),
    url(r'^change_pass_id/(?P<pk>[0-9]*)/$', ChangePassIdView.as_view(), name='change_pass_id'),
    url(r'^activate/(?P<pk>[0-9]*)/$', ActivateView.as_view(), name='activate'),
    url(r'^money_history/$', MoneyHistoryView.as_view(), name='all_money_history'),
    url(r'^keys/$', KeysView.as_view(), name='keys'),
    url(r'^keys/create/$', KeyCreateView.as_view(), name='key_create'),
    url(r'^keys/(?P<pk>[0-9]*)/delete/$', KeyDeleteView.as_view(), name='key_delete'),
    url(r'^keys/(?P<pk>[0-9]*)/update/$', KeyUpdateView.as_view(), name='key_update'),

    url(r'^check_unique/$', CheckUniqueView.as_view(), name='check_unique'),
    url(r'^avatar/change/(?P<pk>[0-9]*)/$', AvatarUpdateView.as_view(), name='change_avatar'),

    url('', include('social.apps.django_app.urls', namespace='social')),

    url(r'^yandex_money_form$', YandexMoneyFormView.as_view(), name='yandex_money_form'),
    url(r'^yandex_money_card$', YandexMoneyCardRedirView.as_view(), name='yandex_money_card'),
    url(r'^yandex_money_redir$', YandexMoneyRedirView.as_view(), name='yandex_money_redir'),
]

DIHT/apps/main/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from main.views import GymView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='home'),
    url(r'^gym/$', GymView.as_view(template_name="gym.html"), name='gym'),
    url(r'^feedback/$', TemplateView.as_view(template_name="feedback.html"), name='feedback'),
]

DIHT/apps/washing/urls.py
from django.conf.urls import url
from washing.views import IndexView, CreateRecordView, CancelRecordView, BlockDayView, UnblockDayView, CheckAccessView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^create_record/$', CreateRecordView.as_view(), name='create_record'),
    url(r'^cancel_record/$', CancelRecordView.as_view(), name='cancel_record'),
    url(r'^block_day/$', BlockDayView.as_view(), name='block_day'),
    url(r'^unblock_day/$', UnblockDayView.as_view(), name='unblock_day'),
    url(r'^access/(([0-9a-fA-F]{2}){4,10})/$', CheckAccessView.as_view(), name='check_access'),
]

DIHT/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

handler400 = 'DIHT.views.custom_400'
handler403 = 'DIHT.views.custom_403'
handler404 = 'DIHT.views.custom_404'
handler405 = 'DIHT.views.custom_405'
handler500 = 'DIHT.views.custom_500'
handler501 = 'DIHT.views.custom_501'
handler502 = 'DIHT.views.custom_502'
handler503 = 'DIHT.views.custom_503'

urlpatterns = [
    url(r'^', include('main.urls', namespace='main')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^washing/', include('washing.urls', namespace='washing')),
    url(r'^activism/', include('activism.urls', namespace='activism')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

DIHT/apps/accounts/views.py
# -*- coding: utf-8 -*-
"""
    Авторы: Гусев Илья
    Дата создания: 22/07/2015
    Версия Python: 3.4
    Версия Django: 1.8.5
    Описание:
        Логика, связанная с профилями пользователей.
        Клиентская часть в signup.js, common.js, profile.js.
        3 вида views - страница, действие, модаль (всплывающее окно).
        Все модали работают с common.js. Если видишь JSON - это туда.
"""
import os
import json
import urllib.parse
import time
from DIHT.settings import BASE_DIR
from django.core.files import File
from django.views.generic.edit import FormView, UpdateView, DeleteView
from django.views.generic import DetailView, View, TemplateView, ListView
from django.contrib.auth.models import User, Group
from django.core.urlresolvers import reverse_lazy
from django.db import transaction
from django.core.mail import EmailMessage
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.views.generic.detail import SingleObjectMixin
from django.http import HttpResponseRedirect
from braces.views import LoginRequiredMixin, UserPassesTestMixin, GroupRequiredMixin
from django.utils import timezone
from django.shortcuts import redirect
from django.conf import settings
from itertools import chain
from accounts.forms import ProfileForm, SignUpForm, ResetPasswordForm, FindForm, \
    MoneyForm, ChangePasswordForm, KeyCreateForm, KeyUpdateForm, ChangePassIdForm, YandexMoneyForm
from accounts.models import Profile, Avatar, MoneyOperation, PaymentsOperation, Key, KeyTransfer
from washing.models import BlackListRecord
from activism.views import get_level
from yandex_money.api import Wallet, ExternalPayment

import logging
logger = logging.getLogger('DIHT.custom')


class JsonErrorsMixin(object):
    """
    Mixin для правильной обработки ошибок в модальных формах.
    Клентская часть в common.js, функция view_modal_errors.
    """
    def form_invalid(self, form):
        super(JsonErrorsMixin, self).form_invalid(form)
        return JsonResponse(form.errors, status=400)


class SignUpView(FormView):
    """
    Страница регистрации пользователя. Пользователь создаётся НЕ активным, нужно подтверждение.
    Дополнительные действия - установка стандартной аватарки.
    """
    template_name = 'accounts/signup.html'
    form_class = SignUpForm
    success_url = reverse_lazy('accounts:signup_ok')

    def form_valid(self, form):
        SignUpView.register_user(form.cleaned_data)
        return super(SignUpView, self).form_valid(form)

    @classmethod
    @transaction.atomic
    def register_user(cls, form):
        user = User.objects.create_user(username=form['username'],
                                        email=form['email'],
                                        password=form['password'],
                                        first_name=form['first_name'],
                                        last_name=form['last_name'])
        Profile.objects.create(user=user,
                               room_number=form['room_number'],
                               group_number=form['group_number'],
                               money=0,
                               mobile=form['mobile'],
                               middle_name=form['middle_name'],
                               hostel=form['hostel'],
                               sex=form['sex'])

        BlackListRecord.objects.create(user=user, is_blocked=False)
        avatar = Avatar.objects.create(user=user)
        with open(os.path.join(BASE_DIR, 'DIHT/static/img/standart_avatar.png'), 'rb') as img_file:
            avatar.img.save("avatar", File(img_file), save=True)
        avatar.save()
        user.is_active = False
        user.save()
        # logger.info('Пользователь '+str(form['first_name'])+' '+str(form['last_name'])+' ('+str(form['username'])+') только что зарегистрировался на сайте.')


class ResetPasswordView(FormView):
    """
    Старница сброса пароля с отправкой письма на e-mail. Никаких проверок не делает.
    """
    template_name = 'accounts/reset_password.html'
    form_class = ResetPasswordForm
    success_url = reverse_lazy('accounts:reset_password_ok')

    def form_valid(self, form):
        user = User.objects.all().filter(username=form.cleaned_data['username'])[0]
        password = User.objects.make_random_password()
        email = EmailMessage(u'Сброс пароля', u'Новый пароль для 2ka.fizteh.ru: ' + password, to=[user.email])
        if email.send() == 1:
            user.set_password(password)
            user.save()
            # logger.info('Пользователь ' + user.get_full_name() + ' (' + user.username + ') изменил свой пароль через функцию восстановления пароля.')
        return super(ResetPasswordView, self).form_valid(form)


class CheckUniqueView(View):
    """
    Действие для проверки уникальности логина и почты.
    Клиентская часть в signup.js, функции check_username и check_email.
    """
    def get(self, request, *args, **kwargs):
        username = request.GET['username']
        email = request.GET['email']
        result = {'username': '0', 'email': '0'}
        if username != '':
            if User.objects.all().filter(username=username).exists():
                result['username'] = '1'
        if email != '':
            if User.objects.all().filter(email=email).exists():
                result['email'] = '1'
        return JsonResponse(result, status=200)


def is_user_key(user, key):
    return key.find(user.last_name + " ") != -1 and \
           key[key.find(".") - 1] == user.first_name[0] and \
           (key[key.rfind(".") - 1] == user.profile.middle_name[0] or key[key.rfind(".") - 1] == ".")


def get_plan_room(user):
    with open("plan.json", 'r') as f:
        content = f.read()
        plan = json.loads(content)
        room = ""
        neighbours = []
        for key, value in plan.items():
            if is_user_key(user, key):
                room = value
                break
        if room == "":
            return -1, neighbours
        for key, value in plan.items():
            if value == room and not is_user_key(user, key):
                neighbours.append(key)
        return room, neighbours


class ProfileView(LoginRequiredMixin, DetailView):
    """
    Страница для отображения профиля
    """
    template_name = 'accounts/profile.html'
    model = Profile

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        user = self.get_object().user
        is_charge = Group.objects.get(name="Ответственные за активистов") in self.request.user.groups.all()
        is_activist = Group.objects.get(name="Активисты") in self.request.user.groups.all()
        context['records'] = user.records.order_by('-datetime_to').reverse()
        context['task_current'] = user.task_set.exclude(status__in=['closed', 'resolved'])
        context['task_responsible'] = sorted(user.tasks_responsible.all(),
                                             key=lambda task: task.datetime_created, reverse=True)
        context['task_hours'] = user.participated.filter(task__status__in=['closed', 'resolved'])
        if user.social_auth.filter(provider='vk-oauth2').exists():
            context['vk'] = user.social_auth.get(provider='vk-oauth2').uid
        if context['profile'].group_number != '':
            grade = int(str(timezone.now().date().year)[-1]) - int(str(context['profile'].group_number)[0])
            if timezone.now().date().month >= 8:
                grade += 1
            if grade > 6 or grade < 0:
                context['grade'] = 'Выпускник/Аспирант'
            else:
                context['grade'] = str(grade) + ' курс'
        context['can_view_tasks'] = (self.request.user == user and is_activist) or self.request.user.is_superuser or is_charge
        context['moderated_money'] = sum(user.moderated_moneyoperations.filter(is_approved=False, amount__gte=0)
                                                                  .values_list('amount', flat=True))
        context['operations'] = user.pointoperations.all()
        context['op_for_hours'] = int(sum(user.participated.filter(task__status__in=['closed'])
                                              .values_list('hours', flat=True)) // 10)
        context['level'] = get_level(user)
        context['plan_room'], context['neighbours'] = get_plan_room(user)
        if 'profile_message' in self.request.session:
            context['profile_message'], context['profile_message_is_error'] = self.request.session['profile_message']
            del self.request.session['profile_message']
        else:
            context['profile_message'], context['profile_message_is_error'] = '', False
        return context


class ProfileUpdateView(LoginRequiredMixin, UserPassesTestMixin, JsonErrorsMixin, UpdateView):
    """
    Модаль для изменения профиля
    """
    model = Profile
    form_class = ProfileForm
    template_name = "accounts/edit_profile.html"
    success_url = reverse_lazy('main:home')
    raise_exception = True

    def test_func(self, user):
        return self.get_object().user == user

    def form_valid(self, form):
        super(ProfileUpdateView, self).form_valid(form)
        return JsonResponse({'url': reverse('accounts:profile', kwargs={'pk': self.get_object().pk})}, status=200)


class AvatarUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    Действие для установки аватарки.
    Клиенсткая часть в profile.js.
    """
    model = Avatar
    fields = ('img', )
    success_url = reverse_lazy('main:home')

    def test_func(self, user):
        return self.get_object().user == user


class SignUpOkView(TemplateView):
    """
    Страница успешной регистрации.
    Показывает людей, к которым нужно обращаться для подтверждения аккаунта.
    """
    template_name = 'accounts/signup_ok.html'

    def get_context_data(self, **kwargs):
        context = super(SignUpOkView, self).get_context_data(**kwargs)

DIHT/apps/main/views.py
from django.views.generic import TemplateView
from django.contrib.auth.models import User, Group


class GymView(TemplateView):
    def get_context_data(self, **kwargs):
        context = super(GymView, self).get_context_data(**kwargs)
        if Group.objects.filter(name="Ответственные за качалку").exists():
            context['charge_gym'] = Group.objects.get(name="Ответственные за качалку").user_set.all()
        return context

DIHT/views.py
from django.shortcuts import render


def custom_400(request):
    values_for_template = {}
    return render(request, 'errors/400.html', values_for_template, status=400)


def custom_403(request):
    values_for_template = {}
    return render(request, 'errors/403.html', values_for_template, status=403)


def custom_404(request):
    values_for_template = {}
    return render(request, 'errors/404.html', values_for_template, status=404)


def custom_405(request):
    values_for_template = {}
    return render(request, 'errors/405.html', values_for_template, status=405)


def custom_500(request):
    values_for_template = {}
    return render(request, 'errors/500.html', values_for_template, status=500)


def custom_501(request):
    values_for_template = {}
    return render(request, 'errors/501.html', values_for_template, status=501)


def custom_502(request):
    values_for_template = {}
    return render(request, 'errors/502.html', values_for_template, status=502)


def custom_503(request):
    values_for_template = {}
    return render(request, 'errors/503.html', values_for_template, status=503)

DIHT/templates/base.html
{% load static from staticfiles %}
{% load has_group %}
<html>
<head>
    <title>Сайт общежития №2 (ФИВТ) - {% block title %} {% endblock %}</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'lib/bootstrap/css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" href="{% static 'css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'css/typographic.css' %}">
    <link rel="shortcut icon" href="{% static 'img/favicon/favicon.ico' %}" type="image/x-icon">

    <script src="{% static 'lib/jquery/js/jquery.js' %}"></script>
    <script src="{% static 'lib/bootstrap/js/bootstrap.js' %}"></script>
    <script src="{% static 'js/common.js' %}"></script>
    <script src="{% static 'js/ajax.csrf.js' %}"></script>
    {% block custom_scripts %} {% endblock %}

    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name='yandex-verification' content='456ed53f77d7ad00' />

    {% include 'autocomplete_light/static.html' %}
</head>
<body style="padding-top:50px;">
    <div id="wrap">
        <nav class = "navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand fivt-logo" href="/"><img width="90" alt="ФИВТ МФТИ" src="/static/img/logo_fivt.png"></a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Общежитие <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li {% block washing_active %} {% endblock %}><a href="{% url 'washing:index' %}">Стиралка</a></li>
                                <li {% block gym_active %} {% endblock %}><a href="{% url 'main:gym' %}">Тренажерный зал</a></li>
                                {% comment %}
                                <li><a href="{% url 'main:accommodation' %}">Поселение</a></li>
                                <li><a href="{% url 'main:announcements' %}">Объявления</a></li>
                                {% endcomment %}
                            </ul>
                        </li>
                        <li {% block activism_active %} {% endblock %}>
                            <a href="{% url 'activism:index' %}">Актив</a>
                        </li>

                        {% comment %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Медиа <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Фото</a></li>
                                <li><a href="#">Видео</a></li>
                            </ul>
                        </li>
                        {% endcomment %}
                    </ul>
                    <ul class = "nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li {% block profile_active %} {% endblock %} class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-user"></i> {{user.get_full_name}}
                                {% if user.profile.money != 0 %}
                                    ({{user.profile.money}} <img style="margin-top:-3px;" src="{% static 'img/icons/coin.png' %}">)
                                {% endif %}
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'accounts:profile' pk=user.profile.pk %}"><i class="fa fa-cogs"></i> Личный кабинет</a><li>
                                {% if user.is_staff %}
                                <li><a href="/admin/"><i class="fa fa-wrench"></i> Панель управления</a></li>
                                {% endif %}
                                {% if user|has_group:'Ответственные за стиралку' or user.is_superuser %}
                                <li><a href="{% url 'accounts:keys' %}"><i class="fa fa-key"></i> Ключи </a></li>
                                {% endif %}
                                {% if user|has_group:'Ответственные за работу с пользователями' or user|has_group:'Ответственные за финансы' or user.is_superuser %}
                                <li><a href="{% url 'accounts:find' %}" data-target="#form-modal"><i class="fa fa-search"></i> Поиск пользователя</a></li>
                                {% endif %}
                                {% if user|has_group:'Ответственные за финансы' or user.is_superuser %}
                                <li><a href="{% url 'accounts:all_money_history' %}" data-target="#form-modal"><i class="fa fa-book"></i> История операций </a></li>
                                {% endif %}
                                <li class="divider"></li>
                                <li><a href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out"></i> Выйти</a><li>
                            </ul>
                    {% else %}
                        <li {% block signup_active %} {% endblock %}><a href="{% url 'accounts:signup' %}"><i class="fa fa-edit"></i>  Регистрация</a></li>
                        <li {% block login_active %} {% endblock %}><a href="{% url 'accounts:login' %}"><i class="fa fa-sign-in"></i>  Вход</a></li>
                    {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        <div id="push"></div>
    </div>

    <div id="footer">
        <div class="container">
            <div class="text-muted credit text-center"><a href="{% url 'main:feedback' %}">Обратная связь</a></div>
        </div>
    </div>
    {% include "modal.html" %}
</body>
</html>

DIHT/templates/cabinet.html
{% extends "base.html" %}

{% block title %} Личный кабинет {% endblock %}

{% block main_active %} class = "active" {% endblock %}

{% block content %}
	
	<div class = "container">
		<div class="page-header">
			<h1>Личный кабинет</h1>
		</div>
		<div class="row">
			<div class="col-md-offset-1 col-md-4"><div class = "well" align="center"><img class = "round avatar" src="/static/img/standart_avatar.png"></img></div></div>
			<div class="col-md-6"><div class = "well">
				<h2>Имя Фамилия (Логин)</h2>
				<h4>Уровень X</h4>
				<h4>Роль</h4>
				<h4>Курс</h4>
			</div></div>
		</div>
		<div class="row">
			<div class = "tabs">
				<ul class = "nav nav-tabs">
					<li class = "active"><a href="#tab-con" data-toggle="tab">Контакты</a></li>
					<li><a href="#tab-tsk" data-toggle="tab">Задачи</a></li>
					<li><a href="#tab-ach" data-toggle="tab">Достижения</a></li>
					<li><a href="#tab-acc" data-toggle="tab">Аккаунт</a></li>
					<li><a href="#tab-wsh" data-toggle="tab">Стиралка</a></li>
				</ul>
				<div class = "tab-content">
					<div class = "tab-pane active" id = "tab-con">
						<button class = "btn btn-primary">Изменить</button>
					</div>
					<div class = "tab-pane" id = "tab-tsk">
					</div>
					<div class = "tab-pane" id = "tab-ach">
					</div>
					<div class = "tab-pane" id = "tab-acc">
					</div>
					<div class = "tab-pane" id = "tab-wsh">
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

DIHT/templates/feedback.html
{% extends "base.html" %}
{% block title %} Обратная связь {% endblock %}
{% block main_active %} class = "active" {% endblock %}
{% block custom_scripts %}{% endblock %}
{% block content %}
    <div class="page-header">
        <h3>Обратная связь</h3>
    </div>
	<div class="col-md-6" style="padding-top:10px;">
        <p>Илья Гусев</p>
        <p>E-mail: ilya.gusev@phystech.edu</p>
        <p>VK: <a href="http://vk.com/allen_gusev">vk.com/allen_gusev</a></p>
    </div>
    <div class="col-md-6" style="padding-top:10px;">
        <p>Денис Шапошников</p>
        <p>E-mail: wokin.shopash@gmail.com</p>
        <p>VK: <a href="http://vk.com/wokinshopash">vk.com/wokinshopash</a></p>
    </div>
    <div class="col-md-12" style="padding-top:20px;">
        <p>Если у вас есть предложения по сайту, оформляйте их в <a href="https://bitbucket.org/mizabrik/2ka/issues">списке задач</a></p>
    </div>
{% endblock %}

DIHT/templates/form.html
{% load add_class %}
{% csrf_token %}
{% for field in form.visible_fields %}
    <label for="{{field.id_for_label}}">{{ field.label }}:</label>
    {{ field|add_class:"form-control" }}
    {{ field.errors }}
{% endfor %}
{% for field in form.hidden_fields %}
    <div style="display:none;">{{ field }}</div>
{% endfor %}
{% if form.errors %}
    {{ form.non_field_errors }}
{% endif %}

DIHT/templates/index.html
{% extends "base.html" %}
{% block title %}  {% endblock %}
{% block main_active %} class = "active" {% endblock %}
{% block custom_scripts %}{% endblock %}
{% block content %}

	<div class="page-header">
        <h3>Сайт общежития №2 ФИВТ</h3>
    </div>
	<div class = "row">
		<div class = "col-md-7">
			<div id="carousel" class="carousel slide hidden-xs hidden-sm">
				<ol class = "carousel-indicators">
					<li data-target="#carousel" class="active disable" data-slide-to="0"></li>
					<li data-target="#carousel" class="disable" data-slide-to="1"></li>
					<li data-target="#carousel" class="disable" data-slide-to="2"></li>
				</ol>
				<div class = "carousel-inner">
					<div class="item active">
						<img src="/static/img/carousel/1.jpg"></img>
						<div class="carousel-caption">
							<p>Тренажерный зал</p>
						</div>
					</div>
					<div class="item">
						<img src="/static/img/carousel/2.jpg"></img>
						<div class="carousel-caption">
							<p>Вход в общежитие</p>
						</div>
					</div>
					<div class="item">
						<img src="/static/img/carousel/3.jpg"></img>
						<div class="carousel-caption">
							<p>Хэллоуин</p>
						</div>
					</div>
				</div>
				<a href="#carousel" class="left carousel-control" data-slide="prev">
					<i style="margin-top:120px" class="fa fa-chevron-left"></i>
				</a>
				<a href="#carousel" class="right carousel-control" data-slide="next">
					<i style="margin-top:120px" class="fa fa-chevron-right"></i>
				</a>
			</div>
            <div class="well" style="margin-top:20px; text-align:center">
                <p>Этот сайт создан для удобной жизни студентов ФИВТ внутри общежития.</p>
                <h4>Навигация</h4>
                <p>
                    <a class="bgrey big-letters" href="{% url 'washing:index' %}"><img src="/static/img/icons/washing.png"></img> Стиралка</a><br>
                    <a class="bgrey big-letters" href="{% url 'main:gym' %}"><img src="/static/img/icons/gym.png"></img> Тренажерный зал</a><br>
                    <a class="bgrey big-letters" href="{% url 'activism:index' %}"><i class="fa fa-thumbs-o-up" style="margin-left:5px;"></i> Актив</a><br>
                </p>
            </div>
		</div>
		<div class = "col-md-5 hidden-xs hidden-sm" id="cell-for-vk-widget">
  			<script type="text/javascript" src="//vk.com/js/api/openapi.js?79"></script>
			<div id="vk_groups"></div>
			<script type="text/javascript">
				VK.Widgets.Group("vk_groups", {mode: 2, width: "375", height: "430"}, 45698612);
			</script>
		</div>
	</div>
			
			

{% endblock %}

DIHT/templates/modal.html
<div class="modal" id="form-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header"></div>
            <div id="form-modal-body" class="modal-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>