DIHT/apps/accounts/urls.py
# -*- coding: utf-8 -*-
"""
    Авторы: Гусев Илья
    Дата создания: 22/07/2015
    Версия Python: 3.4
    Версия Django: 1.8.5
    Описание:
        URL resolver модуля accounts.
"""
from django.conf.urls import url, include
from django.views.generic import TemplateView
from accounts.views import SignUpView, ResetPasswordView, ProfileView, ProfileUpdateView, \
    CheckUniqueView, AvatarUpdateView, SignUpOkView, FindView, AddMoneyView, RemoveMoneyView, \
    ActivateView, MoneyHistoryView, UserMoneyHistoryView, AddPaymentsView, RemovePaymentsView, ChangePasswordView, \
    ApproveMoneyView, KeysView, KeyCreateView, KeyUpdateView, KeyDeleteView, ChargeView, ChangePassIdView, \
    YandexMoneyFormView, YandexMoneyCardRedirView, YandexMoneyRedirView

urlpatterns = [
    url(r'^signup/$', SignUpView.as_view(), name='signup'),
    url(r'^signup_ok/$', SignUpOkView.as_view(), name='signup_ok'),
    url(r'^charge/$', ChargeView.as_view(), name='charge'),

    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),

    url(r'^reset_password/$', ResetPasswordView.as_view(), name='reset_password'),
    url(r'^reset_password_ok/$', TemplateView.as_view(template_name='accounts/reset_password_ok.html'), name='reset_password_ok'),

    url(r'^profile/(?P<pk>[0-9]*)/$', ProfileView.as_view(), name='profile'),
    url(r'^profile/edit/(?P<pk>[0-9]*)/$', ProfileUpdateView.as_view(), name='edit_profile'),
    url(r'^profile/add_money/(?P<pk>[0-9]*)/$', AddMoneyView.as_view(), name='add_money'),
    url(r'^profile/remove_money/(?P<pk>[0-9]*)/$', RemoveMoneyView.as_view(), name='remove_money'),
    url(r'^profile/history_money/(?P<pk>[0-9]*)/$', UserMoneyHistoryView.as_view(), name='history_money'),
    url(r'^profile/add_payments/(?P<pk>[0-9]*)/$', AddPaymentsView.as_view(), name='add_payments'),
    url(r'^profile/remove_payments/(?P<pk>[0-9]*)/$', RemovePaymentsView.as_view(), name='remove_payments'),
    url(r'^profile/find/$', FindView.as_view(), name='find'),
    url(r'^profile/approve_money/(?P<pk>[0-9]*)/$', ApproveMoneyView.as_view(), name='approve_money'),

    url(r'^change_password/(?P<pk>[0-9]*)/$', ChangePasswordView.as_view(), name='change_password'),
    url(r'^change_pass_id/(?P<pk>[0-9]*)/$', ChangePassIdView.as_view(), name='change_pass_id'),
    url(r'^activate/(?P<pk>[0-9]*)/$', ActivateView.as_view(), name='activate'),
    url(r'^money_history/$', MoneyHistoryView.as_view(), name='all_money_history'),
    url(r'^keys/$', KeysView.as_view(), name='keys'),
    url(r'^keys/create/$', KeyCreateView.as_view(), name='key_create'),
    url(r'^keys/(?P<pk>[0-9]*)/delete/$', KeyDeleteView.as_view(), name='key_delete'),
    url(r'^keys/(?P<pk>[0-9]*)/update/$', KeyUpdateView.as_view(), name='key_update'),

    url(r'^check_unique/$', CheckUniqueView.as_view(), name='check_unique'),
    url(r'^avatar/change/(?P<pk>[0-9]*)/$', AvatarUpdateView.as_view(), name='change_avatar'),

    url('', include('social.apps.django_app.urls', namespace='social')),

    url(r'^yandex_money_form$', YandexMoneyFormView.as_view(), name='yandex_money_form'),
    url(r'^yandex_money_card$', YandexMoneyCardRedirView.as_view(), name='yandex_money_card'),
    url(r'^yandex_money_redir$', YandexMoneyRedirView.as_view(), name='yandex_money_redir'),
]

DIHT/apps/main/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from main.views import GymView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='home'),
    url(r'^gym/$', GymView.as_view(template_name="gym.html"), name='gym'),
    url(r'^feedback/$', TemplateView.as_view(template_name="feedback.html"), name='feedback'),
]

DIHT/apps/washing/urls.py
from django.conf.urls import url
from washing.views import IndexView, CreateRecordView, CancelRecordView, BlockDayView, UnblockDayView, CheckAccessView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^create_record/$', CreateRecordView.as_view(), name='create_record'),
    url(r'^cancel_record/$', CancelRecordView.as_view(), name='cancel_record'),
    url(r'^block_day/$', BlockDayView.as_view(), name='block_day'),
    url(r'^unblock_day/$', UnblockDayView.as_view(), name='unblock_day'),
    url(r'^access/(([0-9a-fA-F]{2}){4,10})/$', CheckAccessView.as_view(), name='check_access'),
]

DIHT/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

handler400 = 'DIHT.views.custom_400'
handler403 = 'DIHT.views.custom_403'
handler404 = 'DIHT.views.custom_404'
handler405 = 'DIHT.views.custom_405'
handler500 = 'DIHT.views.custom_500'
handler501 = 'DIHT.views.custom_501'
handler502 = 'DIHT.views.custom_502'
handler503 = 'DIHT.views.custom_503'

urlpatterns = [
    url(r'^', include('main.urls', namespace='main')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^washing/', include('washing.urls', namespace='washing')),
    url(r'^activism/', include('activism.urls', namespace='activism')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

DIHT/apps/accounts/views.py
# -*- coding: utf-8 -*-
"""
    Авторы: Гусев Илья
    Дата создания: 22/07/2015
    Версия Python: 3.4
    Версия Django: 1.8.5
    Описание:
        Логика, связанная с профилями пользователей.
        Клиентская часть в signup.js, common.js, profile.js.
        3 вида views - страница, действие, модаль (всплывающее окно).
        Все модали работают с common.js. Если видишь JSON - это туда.
"""
import os
import json
import urllib.parse
import time
from DIHT.settings import BASE_DIR
from django.core.files import File
from django.views.generic.edit import FormView, UpdateView, DeleteView
from django.views.generic import DetailView, View, TemplateView, ListView
from django.contrib.auth.models import User, Group
from django.core.urlresolvers import reverse_lazy
from django.db import transaction
from django.core.mail import EmailMessage
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.views.generic.detail import SingleObjectMixin
from django.http import HttpResponseRedirect
from braces.views import LoginRequiredMixin, UserPassesTestMixin, GroupRequiredMixin
from django.utils import timezone
from django.shortcuts import redirect
from django.conf import settings
from itertools import chain
from accounts.forms import ProfileForm, SignUpForm, ResetPasswordForm, FindForm, \
    MoneyForm, ChangePasswordForm, KeyCreateForm, KeyUpdateForm, ChangePassIdForm, YandexMoneyForm
from accounts.models import Profile, Avatar, MoneyOperation, PaymentsOperation, Key, KeyTransfer
from washing.models import BlackListRecord
from activism.views import get_level
from yandex_money.api import Wallet, ExternalPayment

import logging
logger = logging.getLogger('DIHT.custom')


class JsonErrorsMixin(object):
    """
    Mixin для правильной обработки ошибок в модальных формах.
    Клентская часть в common.js, функция view_modal_errors.
    """
    def form_invalid(self, form):
        super(JsonErrorsMixin, self).form_invalid(form)
        return JsonResponse(form.errors, status=400)


class SignUpView(FormView):
    """
    Страница регистрации пользователя. Пользователь создаётся НЕ активным, нужно подтверждение.
    Дополнительные действия - установка стандартной аватарки.
    """
    template_name = 'accounts/signup.html'
    form_class = SignUpForm
    success_url = reverse_lazy('accounts:signup_ok')

    def form_valid(self, form):
        SignUpView.register_user(form.cleaned_data)
        return super(SignUpView, self).form_valid(form)

    @classmethod
    @transaction.atomic
    def register_user(cls, form):
        user = User.objects.create_user(username=form['username'],
                                        email=form['email'],
                                        password=form['password'],
                                        first_name=form['first_name'],
                                        last_name=form['last_name'])
        Profile.objects.create(user=user,
                               room_number=form['room_number'],
                               group_number=form['group_number'],
                               money=0,
                               mobile=form['mobile'],
                               middle_name=form['middle_name'],
                               hostel=form['hostel'],
                               sex=form['sex'])

        BlackListRecord.objects.create(user=user, is_blocked=False)
        avatar = Avatar.objects.create(user=user)
        with open(os.path.join(BASE_DIR, 'DIHT/static/img/standart_avatar.png'), 'rb') as img_file:
            avatar.img.save("avatar", File(img_file), save=True)
        avatar.save()
        user.is_active = False
        user.save()
        # logger.info('Пользователь '+str(form['first_name'])+' '+str(form['last_name'])+' ('+str(form['username'])+') только что зарегистрировался на сайте.')


class ResetPasswordView(FormView):
    """
    Старница сброса пароля с отправкой письма на e-mail. Никаких проверок не делает.
    """
    template_name = 'accounts/reset_password.html'
    form_class = ResetPasswordForm
    success_url = reverse_lazy('accounts:reset_password_ok')

    def form_valid(self, form):
        user = User.objects.all().filter(username=form.cleaned_data['username'])[0]
        password = User.objects.make_random_password()
        email = EmailMessage(u'Сброс пароля', u'Новый пароль для 2ka.fizteh.ru: ' + password, to=[user.email])
        if email.send() == 1:
            user.set_password(password)
            user.save()
            # logger.info('Пользователь ' + user.get_full_name() + ' (' + user.username + ') изменил свой пароль через функцию восстановления пароля.')
        return super(ResetPasswordView, self).form_valid(form)


class CheckUniqueView(View):
    """
    Действие для проверки уникальности логина и почты.
    Клиентская часть в signup.js, функции check_username и check_email.
    """
    def get(self, request, *args, **kwargs):
        username = request.GET['username']
        email = request.GET['email']
        result = {'username': '0', 'email': '0'}
        if username != '':
            if User.objects.all().filter(username=username).exists():
                result['username'] = '1'
        if email != '':
            if User.objects.all().filter(email=email).exists():
                result['email'] = '1'
        return JsonResponse(result, status=200)


def is_user_key(user, key):
    return key.find(user.last_name + " ") != -1 and \
           key[key.find(".") - 1] == user.first_name[0] and \
           (key[key.rfind(".") - 1] == user.profile.middle_name[0] or key[key.rfind(".") - 1] == ".")


def get_plan_room(user):
    with open("plan.json", 'r') as f:
        content = f.read()
        plan = json.loads(content)
        room = ""
        neighbours = []
        for key, value in plan.items():
            if is_user_key(user, key):
                room = value
                break
        if room == "":
            return -1, neighbours
        for key, value in plan.items():
            if value == room and not is_user_key(user, key):
                neighbours.append(key)
        return room, neighbours


class ProfileView(LoginRequiredMixin, DetailView):
    """
    Страница для отображения профиля
    """
    template_name = 'accounts/profile.html'
    model = Profile

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        user = self.get_object().user
        is_charge = Group.objects.get(name="Ответственные за активистов") in self.request.user.groups.all()
        is_activist = Group.objects.get(name="Активисты") in self.request.user.groups.all()
        context['records'] = user.records.order_by('-datetime_to').reverse()
        context['task_current'] = user.task_set.exclude(status__in=['closed', 'resolved'])
        context['task_responsible'] = sorted(user.tasks_responsible.all(),
                                             key=lambda task: task.datetime_created, reverse=True)
        context['task_hours'] = user.participated.filter(task__status__in=['closed', 'resolved'])
        if user.social_auth.filter(provider='vk-oauth2').exists():
            context['vk'] = user.social_auth.get(provider='vk-oauth2').uid
        if context['profile'].group_number != '':
            grade = int(str(timezone.now().date().year)[-1]) - int(str(context['profile'].group_number)[0])
            if timezone.now().date().month >= 8:
                grade += 1
            if grade > 6 or grade < 0:
                context['grade'] = 'Выпускник/Аспирант'
            else:
                context['grade'] = str(grade) + ' курс'
        context['can_view_tasks'] = (self.request.user == user and is_activist) or self.request.user.is_superuser or is_charge
        context['moderated_money'] = sum(user.moderated_moneyoperations.filter(is_approved=False, amount__gte=0)
                                                                  .values_list('amount', flat=True))
        context['operations'] = user.pointoperations.all()
        context['op_for_hours'] = int(sum(user.participated.filter(task__status__in=['closed'])
                                              .values_list('hours', flat=True)) // 10)
        context['level'] = get_level(user)
        context['plan_room'], context['neighbours'] = get_plan_room(user)
        if 'profile_message' in self.request.session:
            context['profile_message'], context['profile_message_is_error'] = self.request.session['profile_message']
            del self.request.session['profile_message']
        else:
            context['profile_message'], context['profile_message_is_error'] = '', False
        return context


class ProfileUpdateView(LoginRequiredMixin, UserPassesTestMixin, JsonErrorsMixin, UpdateView):
    """
    Модаль для изменения профиля
    """
    model = Profile
    form_class = ProfileForm
    template_name = "accounts/edit_profile.html"
    success_url = reverse_lazy('main:home')
    raise_exception = True

    def test_func(self, user):
        return self.get_object().user == user

    def form_valid(self, form):
        super(ProfileUpdateView, self).form_valid(form)
        return JsonResponse({'url': reverse('accounts:profile', kwargs={'pk': self.get_object().pk})}, status=200)


class AvatarUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    Действие для установки аватарки.
    Клиенсткая часть в profile.js.
    """
    model = Avatar
    fields = ('img', )
    success_url = reverse_lazy('main:home')

    def test_func(self, user):
        return self.get_object().user == user


class SignUpOkView(TemplateView):
    """
    Страница успешной регистрации.
    Показывает людей, к которым нужно обращаться для подтверждения аккаунта.
    """
    template_name = 'accounts/signup_ok.html'

    def get_context_data(self, **kwargs):
        context = super(SignUpOkView, self).get_context_data(**kwargs)

DIHT/apps/main/views.py
from django.views.generic import TemplateView
from django.contrib.auth.models import User, Group


class GymView(TemplateView):
    def get_context_data(self, **kwargs):
        context = super(GymView, self).get_context_data(**kwargs)
        if Group.objects.filter(name="Ответственные за качалку").exists():
            context['charge_gym'] = Group.objects.get(name="Ответственные за качалку").user_set.all()
        return context

DIHT/views.py
from django.shortcuts import render


def custom_400(request):
    values_for_template = {}
    return render(request, 'errors/400.html', values_for_template, status=400)


def custom_403(request):
    values_for_template = {}
    return render(request, 'errors/403.html', values_for_template, status=403)


def custom_404(request):
    values_for_template = {}
    return render(request, 'errors/404.html', values_for_template, status=404)


def custom_405(request):
    values_for_template = {}
    return render(request, 'errors/405.html', values_for_template, status=405)


def custom_500(request):
    values_for_template = {}
    return render(request, 'errors/500.html', values_for_template, status=500)


def custom_501(request):
    values_for_template = {}
    return render(request, 'errors/501.html', values_for_template, status=501)


def custom_502(request):
    values_for_template = {}
    return render(request, 'errors/502.html', values_for_template, status=502)


def custom_503(request):
    values_for_template = {}
    return render(request, 'errors/503.html', values_for_template, status=503)

DIHT/templates/accounts/add_key.html
{% load add_class %}
<form class="key-create-form" action="{% url 'accounts:key_create' %}" method="POST" autocomplete="off">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Добавить ключ</h3>
    </div>
    <div class="modal-body">
        {% include 'form.html' %}
    </div>
    <div class="modal-footer">
       <a href="#" class="btn btn-danger" data-dismiss="modal">Отмена</a>
       <button class="btn btn-primary" id="modal-submit" type="submit">Добавить</button>
    </div>
</form>

DIHT/templates/accounts/add_money.html
{% load add_class %}
<form class="add-money-form" action="{% url 'accounts:add_money' pk=profile.pk %}" method="POST" autocomplete="off">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Добавить деньги</h3>
    </div>
    <div class="modal-body">
        {% include 'form.html' %}
    </div>
    <div class="modal-footer">
       <a href="#" class="btn btn-danger" data-dismiss="modal">Отмена</a>
       <button class="btn btn-primary" id="modal-submit" type="submit">Подтвердить</button>
    </div>
</form>

DIHT/templates/accounts/add_payments.html
{% load add_class %}
<form class="add-payments-form" action="{% url 'accounts:add_payments' pk=profile.pk %}" method="POST" autocomplete="off">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Увеличить награду</h3>
    </div>
    <div class="modal-body">
        {% include 'form.html' %}
    </div>
    <div class="modal-footer">
       <a href="#" class="btn btn-danger" data-dismiss="modal">Отмена</a>
       <button class="btn btn-primary" id="modal-submit" type="submit">Подтвердить</button>
    </div>
</form>

DIHT/templates/accounts/change_pass_id.html
{% load add_class %}
<form class="change-pass-id-form" action="{% url 'accounts:change_pass_id' pk=profile.pk %}" method="POST" autocomplete="off">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Смена UID пропуска</h3>
    </div>
    <div class="modal-body">
        {% include 'form.html' %}
    </div>
    <div class="modal-footer">
       <a href="#" class="btn btn-danger" data-dismiss="modal">Отмена</a>
       <button class="btn btn-primary" id="modal-submit" type="submit">Сохранить</button>
    </div>
</form>

DIHT/templates/accounts/charge.html
<div class="modal-header"><h3>Ответственные за пользователей</h3></div>
<div id="form-modal-body" class="modal-body">
    {% for user in charge %}
        {{user.get_full_name}}, {{user.profile.mobile}}, {{user.email}}<br>
    {% endfor %}
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
</div>

DIHT/templates/accounts/keys.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load has_group %}
{% load thumbnail %}
{% block title %} Активисты {% endblock %}
{% block activism_table_active %} class = "active" {% endblock %}
{% block custom_scripts %}
{% endblock %}

{% block content %}
<div class="row well namezone">
    <h3 class="task-name nametext"> Ключи </h3>
</div>
<div class = "row pagezone">
    <div class="table-responsive col-sm-12">
    <table class="table">
    {% for key in keys %}
        <tr>
        <td>{{key.name}}
            <a href="{% url 'accounts:key_delete' pk=key.pk %}" class="delete-view"><i class="fa fa-close red"></i></a>
        </td>
        <td>{{key.owner.last_name}}</td>
        <td align="right">
        <a class="btn btn-primary" type="submit" href="{% url 'accounts:key_update' pk=key.pk %}" data-target="#form-modal">Передать</a>
        </td>
        </tr>
    {% endfor %}
    </table>
    </div>
    <a class="btn btn-primary" type="submit" href="{% url 'accounts:key_create' %}" data-target="#form-modal">Добавить</a>
</div>
{% endblock %}

DIHT/templates/accounts/login.html
{% extends "base.html" %}
{% load add_class %}
{% block title %} Вход в систему {% endblock %}
{% block login_active %} class="active" {% endblock %}
{% block content %}
    <div class="col-md-offset-3 col-md-6">
        <div class="page-header"><h2 style="text-align: center;">Страница входа</h2></div>
        <center class="grey">Если вы уже привязали аккаунт:</center>
        <center><span>
            <a href="{% url 'accounts:social:begin' 'vk-oauth2' %}">
                <span class="fa-stack fa-lg" color="#3b579d">
                    <i class="fa fa-square fa-stack-2x"></i>
                    <i class="fa fa-vk fa-stack-1x fa-inverse"></i>
                </span>
            </a>
            <a href="{% url 'accounts:social:begin' 'facebook' %}">
                <span class="fa-stack fa-lg" color="#537599">
                    <i class="fa fa-square fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                </span>
            </a>
        </span></center>
        <br>
        <form class="form-horizontal" method="post" action="./?next={{ redirect_url }}">
            {% csrf_token %}
            <div class="form-group row">
                <label class="control-label col-md-offset-1 col-md-3" for="username">Логин</label>
                <div class="col-md-6">
                    <input type="text" id="username" name = "username" placeholder="Логин" class="form-control">
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-md-offset-1 col-md-3" for="password">Пароль</label>
                <div class="col-md-6">
                    <input type="password" id="password" name = "password" placeholder="Пароль" class="form-control">
                </div>
            </div>
            <div class="form-group row">
                {% if form.errors %}
                    <div class="alert alert-danger">
                        <p class="text-center">Сожалеем, вы неправильно ввели логин или пароль.</p>
                        <p class="text-center">Если ваш аккаунт ещё не активирован, свяжитесь с
                            <a href="{% url 'accounts:charge' %}" data-target="#form-modal">ответственными за пользователей.</a>
                        </p>
                    </div>
                {% endif %}
                <div class="col-md-offset-3 col-md-6">
                    <center>
                        <button class="btn btn-primary btn-block" type="submit">Войти</button><br>
                        <a href="/accounts/signup/">Зарегистрироваться!</a><br>
                        <a href="/accounts/reset_password">Забыл пароль?</a>
                    </center>
                </div>
            </div>
            <input type="hidden" name="next" value="{{next}}" />
        </form>
    </div>
{% endblock %}

DIHT/templates/accounts/remove_money.html
{% load add_class %}
<form class="add-money-form" action="{% url 'accounts:remove_money' pk=profile.pk %}" method="POST" autocomplete="off">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Снять деньги</h3>
    </div>
    <div class="modal-body">
        {% include 'form.html' %}
    </div>
    <div class="modal-footer">
       <a href="#" class="btn btn-danger" data-dismiss="modal">Отмена</a>
       <button class="btn btn-primary" id="modal-submit" type="submit">Подтвердить</button>
    </div>
</form>

DIHT/templates/accounts/remove_payments.html
{% load add_class %}
<form class="remove-payments-form" action="{% url 'accounts:remove_payments' pk=profile.pk %}" method="POST" autocomplete="off">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Уменьшить награду</h3>
    </div>
    <div class="modal-body">
        {% include 'form.html' %}
    </div>
    <div class="modal-footer">
       <a href="#" class="btn btn-danger" data-dismiss="modal">Отмена</a>
       <button class="btn btn-primary" id="modal-submit" type="submit">Подтвердить</button>
    </div>
</form>

DIHT/templates/accounts/reset_password.html
{% extends "base.html" %}
{% load add_class %}
{% block title %}Сброс пароля{% endblock %}

{% block content %}
<div class="col-md-offset-3 col-md-6">
    <div class="page-header"><h2 style="text-align: center;">Сброс пароля</h2></div>
    <form class="form-horizontal" method="post" action=".">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group row" id="group_{{field.name}}">
                <label class="control-label col-md-offset-1 col-md-3" for="{{field.id_for_label}}">{{ field.label }}</label>
                <div class="col-md-6">
                    {{ field|add_class:"form-control" }}
                    {{ field.errors }}
                </div>
            </div>
        {% endfor %}
        {% if form.errors %}
            {{ form.non_field_errors }}
        {% endif %}
        <div class="form-group row">
            <div class="col-md-offset-3 col-md-6">
                <center>
                    <button class="btn btn-primary btn-block" type="submit">Сбросить</button><br>
                    <a href="/accounts/login/">Отмена</a><br>
                </center>
            </div>
        </div>
    </form>
</div>
{% endblock %}

DIHT/templates/accounts/signup.html
{% extends "base.html" %}
{% load add_class %}
{% block signup_active %} class="active" {% endblock %}
{% block title %}Регистрация{% endblock %}
{% block custom_scripts %}<script src="/static/js/signup.js"></script>{% endblock %}
{% block content %}
   <div class="col-md-offset-3 col-md-6">
        <form class="form-horizontal" id="signup_form" action="." method="post">
            <div class="page-header"><h2 style="text-align: center;">Регистрация</h2></div>
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group row" id="group_{{field.name}}">
                    <label class="control-label col-md-offset-1 col-md-3" for="{{field.id_for_label}}">{{ field.label }}</label>
                    <div class="col-md-6">
                        {{ field|add_class:"form-control" }}
                        {{ field.errors }}
                    </div>
                </div>
            {% endfor %}
            {% if form.errors %}
                {{ form.non_field_errors }}
            {% endif %}
            <div class="col-md-offset-3 col-md-6">
                <button class="btn btn-block btn-primary" type="submit" id="subbutton">Зарегистрироваться</button>
            </div>
        </form>
    </div>
    <div style="clear: both"></div>

{% endblock content %}

DIHT/templates/accounts/signup_ok.html
{% extends "base.html" %}
{% load add_class %}
{% block signup_active %} class="active" {% endblock %}
{% block title %}Регистрация{% endblock %}
{% block content %}
<center>
    <div class="page-header"><h2 style="text-align: center;">Регистрация</h2></div>
    <div class="alert alert-success">
        <p>Для завершения регистрации свяжитесь с ответственными за пользователей:</p>
        {% for user in charge %}
            <p class="text-center">{{user.get_full_name}}, {{user.profile.mobile}}, {{user.email}}, {{user.profile.hostel}} общежитие, {{user.profile.room_number}} комната</p>
        {% endfor %}
    </div>
</center>
{% endblock %}

DIHT/templates/accounts/update_key.html
{% load add_class %}
<form class="key-update-form" action="{% url 'accounts:key_update' pk=key.pk %}" method="POST" autocomplete="off">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Передать ключ</h3>
    </div>
    <div class="modal-body">
        {% include 'form.html' %}
    </div>
    <div class="modal-footer">
       <a href="#" class="btn btn-danger" data-dismiss="modal">Отмена</a>
       <button class="btn btn-primary" id="modal-submit" type="submit">Передать</button>
    </div>
</form>

DIHT/templates/accounts/yandex_money.html
{% load add_class %}
<form class="yandex-money-form" action="{% url 'accounts:yandex_money_form' %}" method="POST" autocomplete="off">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Оплата</h3>
    </div>
    <div class="modal-body">
        {% include 'form.html' %}
    </div>
    <div class="modal-footer">
       <a href="#" class="btn btn-danger" data-dismiss="modal">Отмена</a>
       <button class="btn btn-primary" id="modal-submit" type="submit" name="_yandex">Оплатить через Яндекс</button>
       <button class="btn btn-primary" id="modal-submit" type="submit" name="_card">Оплатить с карты</button>
    </div>
</form>