DIHT/apps/accounts/urls.py
# -*- coding: utf-8 -*-
"""
    Авторы: Гусев Илья
    Дата создания: 22/07/2015
    Версия Python: 3.4
    Версия Django: 1.8.5
    Описание:
        URL resolver модуля accounts.
"""
from django.conf.urls import url, include
from django.views.generic import TemplateView
from accounts.views import SignUpView, ResetPasswordView, ProfileView, ProfileUpdateView, \
    CheckUniqueView, AvatarUpdateView, SignUpOkView, FindView, AddMoneyView, RemoveMoneyView, \
    ActivateView, MoneyHistoryView, UserMoneyHistoryView, AddPaymentsView, RemovePaymentsView, ChangePasswordView, \
    ApproveMoneyView, KeysView, KeyCreateView, KeyUpdateView, KeyDeleteView, ChargeView, ChangePassIdView, \
    YandexMoneyFormView, YandexMoneyCardRedirView, YandexMoneyRedirView

urlpatterns = [
    url(r'^signup/$', SignUpView.as_view(), name='signup'),
    url(r'^signup_ok/$', SignUpOkView.as_view(), name='signup_ok'),
    url(r'^charge/$', ChargeView.as_view(), name='charge'),

    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),

    url(r'^reset_password/$', ResetPasswordView.as_view(), name='reset_password'),
    url(r'^reset_password_ok/$', TemplateView.as_view(template_name='accounts/reset_password_ok.html'), name='reset_password_ok'),

    url(r'^profile/(?P<pk>[0-9]*)/$', ProfileView.as_view(), name='profile'),
    url(r'^profile/edit/(?P<pk>[0-9]*)/$', ProfileUpdateView.as_view(), name='edit_profile'),
    url(r'^profile/add_money/(?P<pk>[0-9]*)/$', AddMoneyView.as_view(), name='add_money'),
    url(r'^profile/remove_money/(?P<pk>[0-9]*)/$', RemoveMoneyView.as_view(), name='remove_money'),
    url(r'^profile/history_money/(?P<pk>[0-9]*)/$', UserMoneyHistoryView.as_view(), name='history_money'),
    url(r'^profile/add_payments/(?P<pk>[0-9]*)/$', AddPaymentsView.as_view(), name='add_payments'),
    url(r'^profile/remove_payments/(?P<pk>[0-9]*)/$', RemovePaymentsView.as_view(), name='remove_payments'),
    url(r'^profile/find/$', FindView.as_view(), name='find'),
    url(r'^profile/approve_money/(?P<pk>[0-9]*)/$', ApproveMoneyView.as_view(), name='approve_money'),

    url(r'^change_password/(?P<pk>[0-9]*)/$', ChangePasswordView.as_view(), name='change_password'),
    url(r'^change_pass_id/(?P<pk>[0-9]*)/$', ChangePassIdView.as_view(), name='change_pass_id'),
    url(r'^activate/(?P<pk>[0-9]*)/$', ActivateView.as_view(), name='activate'),
    url(r'^money_history/$', MoneyHistoryView.as_view(), name='all_money_history'),
    url(r'^keys/$', KeysView.as_view(), name='keys'),
    url(r'^keys/create/$', KeyCreateView.as_view(), name='key_create'),
    url(r'^keys/(?P<pk>[0-9]*)/delete/$', KeyDeleteView.as_view(), name='key_delete'),
    url(r'^keys/(?P<pk>[0-9]*)/update/$', KeyUpdateView.as_view(), name='key_update'),

    url(r'^check_unique/$', CheckUniqueView.as_view(), name='check_unique'),
    url(r'^avatar/change/(?P<pk>[0-9]*)/$', AvatarUpdateView.as_view(), name='change_avatar'),

    url('', include('social.apps.django_app.urls', namespace='social')),

    url(r'^yandex_money_form$', YandexMoneyFormView.as_view(), name='yandex_money_form'),
    url(r'^yandex_money_card$', YandexMoneyCardRedirView.as_view(), name='yandex_money_card'),
    url(r'^yandex_money_redir$', YandexMoneyRedirView.as_view(), name='yandex_money_redir'),
]

DIHT/apps/activism/urls.py
# -*- coding: utf-8 -*-
"""
    Авторы: Гусев Илья
    Дата создания:
    Версия Python: 3.4
    Версия Django: 1.8.5
    Описание:
        URL resolver модуля activism.
"""
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from activism.views import EventView, TaskView, IndexView, TaskCreateView, \
    EventsView, EventCreateView, TaskActionView, EventCloseView, UnlockView, \
    SectorView, ActivistsView, TaskLogView, AddPointsView, DeletePointsView, \
    PaymentsView, RatingView, TaskCommentCreateView, TaskCommentUpdateView, \
    TaskCommentDeleteView, EventBestView, ExportPaymentsTableView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^unlock/$', UnlockView.as_view(), name='unlock'),

    url(r'^events/$', EventsView.as_view(), name='events'),
    url(r'^events/create/$', EventCreateView.as_view(), name='create_event'),
    url(r'^events/(?P<pk>[0-9]*)/$', login_required(EventView.as_view()), name='event'),
    url(r'^events/(?P<pk>[0-9]*)/close/$', EventCloseView.as_view(), name='event_close'),
    url(r'^events/(?P<pk>[0-9]*)/best/$', EventBestView.as_view(), name='event_best'),

    url(r'^sectors/(?P<pk>[0-9]*)/$', SectorView.as_view(), name='sector'),

    url(r'^tasks/(?P<pk>[0-9]*)/$', login_required(TaskView.as_view()), name='task'),
    url(r'^tasks/(?P<pk>[0-9]*)/log/$', TaskLogView.as_view(), name='task_log'),
    url(r'^tasks/(?P<pk>[0-9]*)/(?P<action>[0-9_a-z]+)/$', TaskActionView.as_view(), name='task_action'),
    url(r'^tasks/create/$', TaskCreateView.as_view(), name='create_task'),
    url(r'^tasks/(?P<task_pk>[0-9]*)/comments/create/$',
        TaskCommentCreateView.as_view(), name='create_task_comment'),
    url(r'^tasks/(?P<task_pk>[0-9]*)/comments/(?P<pk>[0-9]*)/update/$',
        TaskCommentUpdateView.as_view(), name='update_task_comment'),
    url(r'^tasks/(?P<task_pk>[0-9]*)/comments/(?P<pk>[0-9]*)/delete/$',
        TaskCommentDeleteView.as_view(), name='delete_task_comment'),

    url(r'^activists/$', ActivistsView.as_view(), name='activists'),
    url(r'^activists/(?P<pk>[0-9]*)/add_points/$', AddPointsView.as_view(), name='add_points'),
    url(r'^activists/(?P<pk>[0-9]*)/delete_points/$', DeletePointsView.as_view(), name='delete_points'),

    url(r'^payments/$', PaymentsView.as_view(), name='payments'), 
    url(r'^payments/as_csv/$', ExportPaymentsTableView.as_view(), name='download_csv'),
    url(r'^rating/$', RatingView.as_view(), name='rating'),
]

DIHT/apps/main/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from main.views import GymView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='home'),
    url(r'^gym/$', GymView.as_view(template_name="gym.html"), name='gym'),
    url(r'^feedback/$', TemplateView.as_view(template_name="feedback.html"), name='feedback'),
]

DIHT/apps/washing/urls.py
from django.conf.urls import url
from washing.views import IndexView, CreateRecordView, CancelRecordView, BlockDayView, UnblockDayView, CheckAccessView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^create_record/$', CreateRecordView.as_view(), name='create_record'),
    url(r'^cancel_record/$', CancelRecordView.as_view(), name='cancel_record'),
    url(r'^block_day/$', BlockDayView.as_view(), name='block_day'),
    url(r'^unblock_day/$', UnblockDayView.as_view(), name='unblock_day'),
    url(r'^access/(([0-9a-fA-F]{2}){4,10})/$', CheckAccessView.as_view(), name='check_access'),
]

DIHT/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

handler400 = 'DIHT.views.custom_400'
handler403 = 'DIHT.views.custom_403'
handler404 = 'DIHT.views.custom_404'
handler405 = 'DIHT.views.custom_405'
handler500 = 'DIHT.views.custom_500'
handler501 = 'DIHT.views.custom_501'
handler502 = 'DIHT.views.custom_502'
handler503 = 'DIHT.views.custom_503'

urlpatterns = [
    url(r'^', include('main.urls', namespace='main')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^washing/', include('washing.urls', namespace='washing')),
    url(r'^activism/', include('activism.urls', namespace='activism')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

DIHT/apps/activism/views.py
# -*- coding: utf-8 -*-
"""
    Авторы: Гусев Илья
    Дата создания:
    Версия Python: 3.4
    Версия Django: 1.8.5
    Описание:
        Самый главный файл - логика, связанная с активистами.
        Клиентская часть в activism.js и activism/*.js
        3 вида views - страница, действие, модаль (всплывающее окно).
        Все модали работают с common.js. Если видишь JSON - это туда.
"""
import datetime as dt
from itertools import chain
from collections import OrderedDict
from copy import deepcopy
from django.db.models import Count
from django.core.exceptions import PermissionDenied
from django.views.generic import ListView, View, CreateView, TemplateView, DetailView, DeleteView
from django.views.generic.edit import UpdateView
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.models import User, Group
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.utils import timezone
from braces.views import LoginRequiredMixin, GroupRequiredMixin, UserPassesTestMixin
from reversion import get_for_object
from activism.models import Event, Task, AssigneeTask, Sector, PointOperation, ResponsibleEvent, TaskComment
from activism.forms import TaskForm, EventForm, TaskCreateForm, PointForm, TaskCommentForm
from activism.utils import global_checks, get_level, get_level_by_num
from accounts.models import PaymentsOperation
from django.db.models import Sum
import math
import csv

"""
    Mixins
"""


class PostAccessMixin(SingleObjectMixin):
    """
    Mixin для проверки прав. От UserPassesTestMixin отличается тем, что работает только с POST частью.
    """
    def post(self, request, *args, **kwargs):
        checks = global_checks(request.user, self.get_object())
        if checks['is_responsible'] or checks['can_all'] or checks['is_main']:
            return super(PostAccessMixin, self).post(request, args, kwargs)
        else:
            raise PermissionDenied


class DefaultContextMixin(object):
    """
    Mixin для введения общего конекста.
    """
    def get_context_data(self, **kwargs):
        context = super(DefaultContextMixin, self).get_context_data(**kwargs)
        user = self.request.user
        context['events'] = Event.objects.all()
        context['sectors'] = Sector.objects.all()
        context['users'] = User.objects.all()
        obj = self.get_object() if hasattr(self, 'object') else None
        context.update(global_checks(user, obj))
        return context


class JsonCreateMixin(object):
    """
    Mixin для внедрения при создании объекта.
    Автоматически назначает текущего пользователя ответственным и возвращает JSON.
    """
    def form_valid(self, form):
        result = super(JsonCreateMixin, self).form_valid(form)
        if not isinstance(form.instance, Event):
            form.instance.responsible.add(self.request.user)
        else:
            ResponsibleEvent.objects.create(event=form.instance, user=self.request.user)
        return JsonResponse({'url': result.url}, status=200)


class JsonErrorsMixin(object):
    """
    Mixin для правильной обработки ошибок в модальных формах.
    Клентская часть в common.js, функция view_modal_errors.
    """
    def form_invalid(self, form):
        super(JsonErrorsMixin, self).form_invalid(form)
        return JsonResponse(form.errors, status=400)


"""
    Action views
"""


class UnlockView(LoginRequiredMixin, View):
    """
    Действие для открытия доступа к модулю.
    """
    raise_exception = True

    def get(self, request, *args, **kwargs):
        user = request.user
        user.groups.add(Group.objects.get(name="Активисты"))
        return HttpResponseRedirect(reverse('activism:index'))


class EventCreateView(LoginRequiredMixin, GroupRequiredMixin, JsonCreateMixin, JsonErrorsMixin, CreateView):
    """
    Модаль для создания мероприятия.
    """
    model = Event
    template_name = 'activism/event_create.html'
    fields = ('name', 'sector')
    group_required = ["Руководящая группа", "Ответственные за активистов"]
    raise_exception = True


# EventClosingView  - begin
"""
    Действие закрытия мероприятия.
    Такая сложная логика из-за требования руководителей секторов назначать ОР по завершении мероприятия
    и разрешать конфликты.
    Из-за большого объёма разбито на методы.
"""


def get_event_assignees(event):
    assignees = set()
    for task in Task.objects.filter(event=event.pk):
        assignees = assignees.union(set(task.assignees.all()))
    return list(assignees)


def check_user_can_create_gp(user):
    checks = global_checks(user)
    return checks['is_main'] or checks['can_all']


def check_event_closing(event):
    assignees = get_event_assignees(event)
    has_main = False
    all_done = True
    has_conflicts = False
    only_main_gp = True
    for u in [User.objects.get(pk=i) for i in ResponsibleEvent.objects.filter(event=event)
                                                              .values_list('user', flat=True)]:
        if Group.objects.get(name="Руководящая группа") in u.groups.all():
            has_main = True

    for entity in ResponsibleEvent.objects.filter(event=event):
        if (has_main and
            Group.objects.get(name="Руководящая группа") in entity.user.groups.all() and
            not entity.done) or \
           (not has_main and not entity.done):
            all_done = False

    for assignee in assignees:
        op = PointOperation.objects.filter(user=assignee, description="За " + event.name)
        if op.count() > 1:
            has_conflicts = True
        elif op.exists():
            if not check_user_can_create_gp(op[0].moderator):
                only_main_gp = False

    return {"all_done": all_done,
            "only_main_gp": only_main_gp,
            "has_conflicts": has_conflicts,
            "all_ok": all_done and only_main_gp and not has_conflicts}


def create_point_op(request, assignee, event, user):
    gp = request.POST.get("gp_"+str(assignee.pk))
    if gp is not None and gp != '':
        if 0 < int(gp) < 3:
            PointOperation.objects.create(user=assignee, amount=int(gp), timestamp=timezone.now(),
                                          description="За " + event.name, moderator=user)


class EventCloseView(GroupRequiredMixin, LoginRequiredMixin, DefaultContextMixin, DetailView):
    model = Event
    group_required = "Активисты"
    template_name = "activism/event_close.html"
    raise_exception = True

    def get_context_data(self, **kwargs):
        context = super(EventCloseView, self).get_context_data(**kwargs)
        event = self.get_object()
        user = self.request.user
        gps = {}
        assignees = get_event_assignees(event)
        # Заполняем таблицу ОР назначенных и вливаем её в контекст
        for assignee in assignees:
            op = assignee.pointoperations.filter(description="За "+event.name, moderator=user)
            if op.exists():
                gps[assignee.pk] = op[0]
        context['assignees'] = assignees
        context['gps'] = gps

        # Если юзер ответственный за активистов или суперюзер,
        # он может видеть всю таблицу от всех ответственных с конфликтами
        if context['can_all']:
            gp_table = OrderedDict()
            ordered_assignees = OrderedDict()
            for responsible in event.responsible.all():
                ordered_assignees[responsible] = 0
            # Заполняем gp_table
            for assignee in assignees:
                gp_table[assignee] = deepcopy(ordered_assignees)
                for responsible in event.responsible.all():
                    gps = PointOperation.objects.filter(user=assignee, moderator=responsible,
                                                        description="За " + event.name)
                    if gps.exists():
                        gp_table[assignee][responsible] = gps[0].amount
            conflict_users = PointOperation.objects.filter(description="За "+event.name)\
                                                   .values('user')\
                                                   .annotate(Count('id')).order_by()\
                                                   .filter(id__count__gt=1)\
                                                   .values_list('user', flat=True)
            #
            not_main_users = []
            for assignee in assignees:
                op = PointOperation.objects.filter(user=assignee, description="За " + event.name)
                if op.count() == 1 and not check_user_can_create_gp(op[0].moderator):
                    not_main_users.append(assignee.id)
            responsible = OrderedDict()
            for res in ordered_assignees.keys():
                responsible[res] = ResponsibleEvent.objects.get(event=event, user=res).done

            can_resolve = context['can_all']
            if context['is_responsible'] and context['can_all']:
                can_resolve = can_resolve and ResponsibleEvent.objects.get(event=event, user=user).done

            context['can_resolve'] = can_resolve
            context['gp_table'] = gp_table
            context['responsible'] = responsible
            context['conflict_users'] = conflict_users
            context['not_main_users'] = not_main_users
        return context

    def post(self, request, *args, **kwargs):
        event = self.get_object()
        user = request.user
        checks = global_checks(user, event)
        tasks_ok = (event.tasks.exclude(status="closed").count() == 0)
        assignees = get_event_assignees(event)

        can_resolve = checks['can_all']
        if checks['is_responsible'] and checks['can_all']:
            can_resolve = can_resolve and ResponsibleEvent.objects.get(event=event, user=user).done

        if tasks_ok:
            if can_resolve:
                for assignee in assignees:

DIHT/templates/activism/add_points.html
{% load add_class %}
<form class="add-points-form" action="{% url 'activism:add_points' pk=user.pk %}" method="POST" autocomplete="off">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Добавить очки роста</h3>
    </div>
    <div class="modal-body">
        {% include 'form.html' %}
    </div>
    <div class="modal-footer">
       <a href="#" class="btn btn-danger" data-dismiss="modal">Отмена</a>
       <button class="btn btn-primary" id="modal-submit" type="submit">Подтвердить</button>
    </div>
</form>

DIHT/templates/activism/event_best.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load add_class %}
{% load thumbnail %}
{% load list_utils %}
{% block title %} Закрыть мероприятие {% endblock %}
{% block custom_scripts %}
    <script src="{% static 'js/activism.js' %}"></script>
    <script src="{% static 'js/activism/event_best.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/activism.css' %}">{% endblock %}
{% block content %}
<div class="row well namezone">
    <h3>Лучшие активисты в <span class="event-name">{{event.name}}</span></h3>
</div>
<div class = "row pagezone">
    <div class="col-md-10 col-md-offset-1">
    <table class="table">
        {% for assignee, operation in star_table.items%}
        <tr>
            <th width="50%" style="text-align: center;"> {{ assignee.get_full_name }}</th>
            <td width="50%" style="text-align: center;">
                {% if operation %}
                <a href="{% url 'activism:delete_points' pk=operation.pk %}" class="delete-view">
                    <i class="fa fa-star yellow fa-lg"></i>
                </a>
                {% else %}
                <a href="{% url 'activism:add_points' pk=assignee.pk %}" class="event-best-on">
                    <i class="fa fa-star-o fa-lg"></i>
                </a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
    </div>
</div>
{% endblock %}

DIHT/templates/activism/event_create.html
{% load add_class %}
<form class="event-create-form" action="{% url 'activism:create_event' %}" method="POST" autocomplete="off">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Создание мероприятие</h3>
    </div>
    <div class="modal-body">
        {% include 'form.html' %}
    </div>
    <div class="modal-footer">
       <a href="#" class="btn btn-danger" data-dismiss="modal">Отмена</a>
       <button class="btn btn-primary" id="modal-submit" type="submit">Сохранить</button>
    </div>
</form>

DIHT/templates/activism/events.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load has_group %}
{% block title %} Мероприятия {% endblock %}
{% block custom_scripts %}
    <script src="{% static 'js/activism.js' %}"></script>
	<link rel="stylesheet" href="{% static 'css/activism.css' %}">
{% endblock %}
{% block content %}

<div class="row well namezone">
    <h3 class="task-name nametext"> Мероприятия </h3>
</div>
<div class = "row pagezone">
	<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        {% for event in events %}
		<div class="panel panel-default">
			<div class="panel-heading event-pan" role="tab" id="heading{{event.pk}}" data-toggle="collapse" data-parent="#accordion" href="#body{{event.pk}}" aria-expanded="false" aria-controls="body{{event.pk}}">
				<h4>{{ event.name }}</h4>
			</div>
			<div id="body{{event.pk}}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading{{event.id}}">
				<div class="panel-body">
                    <p style = "margin-bottom:10px;">
					{% if event.description %}{{ event.description }}
                    {% else %}Нет описания{% endif %}
                    </p>
                    <span class="grey">Дата проведения: </span><span>{{ event.date_held }}</span>
                    <a class="pull-right" href="{% url 'activism:event' pk=event.pk %}">Страница мероприятия <i class="fa fa-chevron-right"></i></a>
				</div>
			</div>
		</div>
        {% endfor %}
	</div>
    
    {% if can_all or is_main %}
    
    <center><a class="btn btn-default robotobold"
               href="{% url 'activism:create_event'%}"
               data-target="#form-modal">
        <i class="fa fa-calendar fa-lg" style="margin-right:10px"></i> Новое мероприятие </i>
    </a></center>
    {% endif %}
</div>
{% endblock %}

DIHT/templates/activism/payments.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load has_group %}
{% load thumbnail %}
{% block title %} Активисты {% endblock %}
{% block activism_table_active %} class = "active" {% endblock %}
{% block custom_scripts %}
    <script src="{% static 'js/activism.js' %}"></script>
    <script src="{% static 'js/activism/payments.js' %}"></script>
	<link rel="stylesheet" href="{% static 'css/activism.css' %}">
{% endblock %}

{% block content %}
<div class="row well namezone">
    <h3 class="task-name nametext"> Выплаты </h3>
</div>
<div class = "row pagezone">
    <div class="col-sm-3">
        <form class="form" method="get" action="./" name="filter">
            <label class="control-label" for="const">Константа: </label>
            <input id="const" type="number" class="form-control" name="const" step="any" min="0" max="100000" value="{{const|stringformat:'.10g'}}">
            <br>
            <label class="control-label" for="begin">Начало отчётного периода: </label>
            <input id="begin" type="date" class="form-control" name="begin" value="{{begin|date:'Y-m-d'}}">
            <br>
            <label class="control-label" for="end">Конец отчётного периода: </label>
            <input id="end" type="date" class="form-control" name="end" value="{{end|date:'Y-m-d'}}">
            <br>
            <center>
                <button class="btn btn-primary" type="submit">Посчитать</button>
                <button id="payments_apply" class="btn btn-danger action confirm" type="submit">Утвердить</button>
                <button id="download_csv" class="btn btn-info">Сформировать CSV</button>
            </center>
        </form>
    </div>

    <div class="table-responsive col-sm-9">
    <table class="table table-bordered">
        <tr>
            <th class="text-center">Активист</th>
            <th class="text-center">Управление</th>
            <th class="text-center">Группа</th>
            <th class="text-center">Часы</th>
            <th class="text-center">Эффективные часы</th>
            <th class="text-center">Невыплаченно ранее</th>
            <th class="text-center">Деньги за период</th>
        </tr>
    {% for record in records %}
        <tr>
            <td style = "padding: 1px 10px;">
                <a href = "{% url 'accounts:profile' pk=record.user.profile.pk %}">{{record.user.last_name}} {{record.user.first_name}} {{record.user.profile.middle_name}}</a>
            </td>
            <td class="">
                <span>
                    <a href="{% url 'accounts:add_payments' pk=record.user.profile.pk %}" class="btn btn-sm btn-default" data-target="#form-modal"><i class="fa fa-plus green"></i></a>
                    <a href="{% url 'accounts:remove_payments' pk=record.user.profile.pk %}" class="btn btn-sm btn-default" data-target="#form-modal"><i class="fa fa-minus red"></i></a>
                </span>
            </td>
            <td class="">
                {{record.user.profile.group_number}}
            </td>
            <td class="">
                {{record.hours|stringformat:'.2f'}}
            </td>
            <td class="">
                {{record.effective_hours|stringformat:'.2f'}}
            </td>
            <td class="">
                {{record.holded_payment|stringformat:'.0f'}}
            </td>
            <td>
                {{record.payment|stringformat:'.0f'}}
            </td>
        </tr>
    {% endfor %}
        <tr>
            <td class="">
                Сумма
            </td>
            <td class="">
            </td>
            <td class="">
            </td>
            <td class="">
            </td>
            <td class="">
            </td><td class="">
                {{holded_payment_sum|stringformat:'.0f'}}
            </td>
            <td>
                {{payment_sum|stringformat:'.0f'}}
            </td>
        </tr>
    </table>
    </div>
</div>
{% include "activism/confirm_modal.html" %}
{% endblock %}

DIHT/templates/activism/sector.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load add_class %}
{% load thumbnail %}
{% block title %} Сектор {% endblock %}
{% block custom_scripts %}
    <script src="{% static 'js/activism.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/activism.css' %}">{% endblock %}
{% block content %}
<div class="row well namezone">
    <h3 class="nametext">{{sector.name}}</h3>
</div>
<div class = "row pagezone">
    <div class="col-md-4 hidden-sm hidden-xs">
        {% if sector.photo %}
        <img src="{{MEDIA_URL}}{{sector.photo.url}}" class="img-responsive"></img>
        {% endif %}
    </div>
    <div class="col-md-8">
        <p style="margin-bottom:10px;"><span class="robotobold big-letters" style="margin-right:10px;">Руководитель:</span>
        <a href="{% url 'accounts:profile' pk=sector.main.profile.pk %}">
        {% if sector.main.avatar.img %}
            {% thumbnail sector.main.avatar.img "35x35" crop="center" as pic %}
            <img src="{{ pic.url }}" class="avatar">
            {% endthumbnail %}
        {% endif %}
            <span class="big-letters" style="margin-left:5px;">{{ sector.main.get_full_name }}</span></a></p>
        {{ sector.description|linebreaksbr }}
    </div>
    <div class="col-md-offset-2 col-md-8" style="margin-top: 20px;">
        <div class="panel panel-default sevent-pan">
            <div class="panel-heading"><i class="fa fa-calendar fa-fw" style="margin-right:5px;"></i>&nbsp;Ближайшие мероприятия сектора
            </div>
            <div class="panel-body" id="sector-events">
                {% for event in sector.events.all %}
                    {% if event.status == 'open' %}
                        <a class="" href="{% url 'activism:event' pk=event.pk %}">{{ event.name }}</a><br>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
            
    </div>
</div>

{% endblock %}